const vocabulary = {
      "Salam": [
		 { word: "おはようございます", meaning: "Selamat pagi" },
		 { word: "こんにちは", meaning: "Selamat siang" },
		 { word: "こんばんは", meaning: "Selamat malam" },
		 { word: "おやすみなさい", meaning: "Selamat beristirahat" },
		 { word: "ありがとう", meaning: "Terima kasih (kasual)" },
		 { word: "ありがとうございます", meaning: "Terima kasih (formal)" },
		 { word: "どういたしまして", meaning: "Sama-sama" },
		 { word: "すみません", meaning: "Permisi / Maaf" },
		 { word: "ごめんなさい", meaning: "Maaf (kasual)" },
		 { word: "もうしわけありませんでした", meaning: "Mohon maaf sekali" },
		 { word: "たのみます", meaning: "Tolong" },
		 { word: "よろしくおねがいします", meaning: "Mohon bantuannya" },
		 { word: "いらっしゃいませ", meaning: "Selamat datang" },
		 { word: "ようこそ／いらっしゃい", meaning: "Selamat datang" },
		 { word: "いってきます", meaning: "Saya pergi" },
		 { word: "いってらっしゃい", meaning: "Selamat jalan" },
		 { word: "ただいま", meaning: "Saya pulang" },
		 { word: "おかえりなさい", meaning: "Selamat datang kembali" },
		 { word: "さようなら", meaning: "Selamat tinggal" },
		 { word: "またあいましょう", meaning: "Sampai jumpa" },
		 { word: "しつれいします", meaning: "Permisi (sopan)" },
	   { word: "おさきにしつれいします", meaning: "Permisi duluan" },
		 { word: "おつかれさまです", meaning: "Terima kasih atas kerja kerasnya" },
		 { word: "いただきます", meaning: "Saya makan/minum" },
		 { word: "ごちそうさまでした", meaning: "Terima kasih atas hidangannya" },
		 { word: "おめでとうございます", meaning: "Selamat" },
		 { word: "あけましておめでとうございます", meaning: "Selamat tahun baru" },
		 { word: "きをつけてください", meaning: "Hati-hati ya" },
		 { word: "おくやみもうしあげます", meaning: "Turut berduka cita" },
		 { word: "おだいじに", meaning: "Semoga lekas sembuh" },
		 { word: "どうぞ", meaning: "Silakan" } 
      ],
      "Angka": [
        { "word": "一（いち）", "meaning": "1" },
		  { "word": "二（に）", "meaning": "2" },
		  { "word": "三（さん）", "meaning": "3" },
		  { "word": "四（よん / し）", "meaning": "4" },
		  { "word": "五（ご）", "meaning": "5" },
		  { "word": "六（ろく）", "meaning": "6" },
		  { "word": "七（なな / しち）", "meaning": "7" },
		  { "word": "八（はち）", "meaning": "8" },
		  { "word": "九（きゅう / く）", "meaning": "9" },
		  { "word": "十（じゅう）", "meaning": "10" },
		{ "word": "十一（じゅういち）", "meaning": "11" },
  { "word": "十二（じゅうに）", "meaning": "12" },
  { "word": "二十（にじゅう）", "meaning": "20" },
  { "word": "二十一（にじゅういち）", "meaning": "21" },
  { "word": "二十二（にじゅうに）", "meaning": "22" },
  { "word": "三十（さんじゅう）", "meaning": "30" },
  { "word": "四十（よんじゅう）", "meaning": "40" },
  { "word": "五十（ごじゅう）", "meaning": "50" },
  { "word": "百（ひゃく）", "meaning": "100" },
  { "word": "二百（にひゃく）", "meaning": "200" },
  { "word": "三百（さんびゃく）", "meaning": "300" },
  { "word": "四百（よんひゃく）", "meaning": "400" },
  { "word": "五百（ごひゃく）", "meaning": "500" },
  { "word": "六百（ろっぴゃく）", "meaning": "600" },
  { "word": "七百（ななひゃく）", "meaning": "700" },
  { "word": "八百（はっぴゃく）", "meaning": "800" },
  { "word": "九百（きゅうひゃく）", "meaning": "900" },
  { "word": "千（せん）", "meaning": "1.000" },
  { "word": "一万（いちまん）", "meaning": "10.000" },
  { "word": "百万（ひゃくまん）", "meaning": "1.000.000" },
  { "word": "一千万（いっせんまん）", "meaning": "10.000.000" },
  { "word": "一億（いちおく）", "meaning": "100.000.000" }
      ],
	  "Hitung": [
	  { "word": "一台（いちだい）", "meaning": "1 unit" },
  { "word": "二台（にだい）", "meaning": "2 unit" },
  { "word": "三台（さんだい）", "meaning": "3 unit" },
  { "word": "四台（よんだい）", "meaning": "4 unit" },
  { "word": "五台（ごだい）", "meaning": "5 unit" },
  { "word": "六台（ろくだい）", "meaning": "6 unit" },
  { "word": "七台（ななだい）", "meaning": "7 unit" },
  { "word": "八台（はちだい）", "meaning": "8 unit" },
  { "word": "九台（きゅうだい）", "meaning": "9 unit" },
  { "word": "十台（じゅうだい）", "meaning": "10 unit" },
	  { "word": "一杯（いっぱい）", "meaning": "1 gelas" },
  { "word": "二杯（にはい）", "meaning": "2 gelas" },
  { "word": "三杯（さんばい）", "meaning": "3 gelas" },
  { "word": "四杯（よんはい）", "meaning": "4 gelas" },
  { "word": "五杯（ごはい）", "meaning": "5 gelas" },
  { "word": "六杯（ろっぱい）", "meaning": "6 gelas" },
  { "word": "七杯（ななはい）", "meaning": "7 gelas" },
  { "word": "八杯（はっぱい）", "meaning": "8 gelas" },
  { "word": "九杯（きゅうはい）", "meaning": "9 gelas" },
  { "word": "十杯（じゅっぱい / じっぱい）", "meaning": "10 gelas" },
	   { "word": "一冊（いっさつ）", "meaning": "1 buku" },
  { "word": "二冊（にさつ）", "meaning": "2 buku" },
  { "word": "三冊（さんさつ）", "meaning": "3 buku" },
  { "word": "四冊（よんさつ）", "meaning": "4 buku" },
  { "word": "五冊（ごさつ）", "meaning": "5 buku" },
  { "word": "六冊（ろくさつ）", "meaning": "6 buku" },
  { "word": "七冊（ななさつ）", "meaning": "7 buku" },
  { "word": "八冊（はっさつ）", "meaning": "8 buku" },
  { "word": "九冊（きゅうさつ）", "meaning": "9 buku" },
  { "word": "十冊（じゅっさつ / じっさつ）", "meaning": "10 buku" },
  { "word": "一枚（いちまい）", "meaning": "1 lembar" },
  { "word": "二枚（にまい）", "meaning": "2 lembar" },
  { "word": "三枚（さんまい）", "meaning": "3 lembar" },
  { "word": "四枚（よんまい）", "meaning": "4 lembar" },
  { "word": "五枚（ごまい）", "meaning": "5 lembar" },
  { "word": "六枚（ろくまい）", "meaning": "6 lembar" },
  { "word": "七枚（ななまい）", "meaning": "7 lembar" },
  { "word": "八枚（はちまい）", "meaning": "8 lembar" },
  { "word": "九枚（きゅうまい）", "meaning": "9 lembar" },
  { "word": "十枚（じゅうまい）", "meaning": "10 lembar" },
  { "word": "一つ（ひとつ）", "meaning": "1 buah" },
  { "word": "二つ（ふたつ）", "meaning": "2 buah" },
  { "word": "三つ（みっつ）", "meaning": "3 buah" },
  { "word": "四つ（よっつ）", "meaning": "4 buah" },
  { "word": "五つ（いつつ）", "meaning": "5 buah" },
  { "word": "六つ（むっつ）", "meaning": "6 buah" },
  { "word": "七つ（ななつ）", "meaning": "7 buah" },
  { "word": "八つ（やっつ）", "meaning": "8 buah" },
  { "word": "九つ（ここのつ）", "meaning": "9 buah" },
  { "word": "十（とお）", "meaning": "10 buah" },
  { "word": "一本（いっぽん）", "meaning": "1 batang" },
  { "word": "二本（にほん）", "meaning": "2 batang" },
  { "word": "三本（さんぼん）", "meaning": "3 batang" },
  { "word": "四本（よんほん）", "meaning": "4 batang" },
  { "word": "五本（ごほん）", "meaning": "5 batang" },
  { "word": "六本（ろっぽん）", "meaning": "6 batang" },
  { "word": "七本（ななほん）", "meaning": "7 batang" },
  { "word": "八本（はっぽん）", "meaning": "8 batang" },
  { "word": "九本（きゅうほん）", "meaning": "9 batang" },
  { "word": "十本（じゅっぽん）", "meaning": "10 batang" },
  { "word": "一回（いっかい）", "meaning": "1 kali" },
  { "word": "二回（にかい）", "meaning": "2 kali" },
  { "word": "三回（さんかい）", "meaning": "3 kali" },
  { "word": "四回（よんかい）", "meaning": "4 kali" },
  { "word": "五回（ごかい）", "meaning": "5 kali" },
  { "word": "六回（ろっかい）", "meaning": "6 kali" },
  { "word": "七回（ななかい）", "meaning": "7 kali" },
  { "word": "八回（はっかい）", "meaning": "8 kali" },
  { "word": "九回（きゅうかい）", "meaning": "9 kali" },
  { "word": "十回（じゅっかい / じっかい）", "meaning": "10 kali" },
  { "word": "一人（ひとり）", "meaning": "1 orang" },
  { "word": "二人（ふたり）", "meaning": "2 orang" },
  { "word": "三人（さんにん）", "meaning": "3 orang" },
  { "word": "四人（よにん）", "meaning": "4 orang" },
  { "word": "五人（ごにん）", "meaning": "5 orang" },
  { "word": "六人（ろくにん）", "meaning": "6 orang" },
  { "word": "七人（しちにん / ななにん）", "meaning": "7 orang" },
  { "word": "八人（はちにん）", "meaning": "8 orang" },
  { "word": "九人（きゅうにん）", "meaning": "9 orang" },
  { "word": "十人（じゅうにん）", "meaning": "10 orang" },
  { "word": "一匹（いっぴき）", "meaning": "1 ekor (Hewan Kecil)" },
  { "word": "二匹（にひき）", "meaning": "2 ekor" },
  { "word": "三匹（さんびき）", "meaning": "3 ekor" },
  { "word": "四匹（よんひき）", "meaning": "4 ekor" },
  { "word": "五匹（ごひき）", "meaning": "5 ekor" },
  { "word": "六匹（ろっぴき）", "meaning": "6 ekor" },
  { "word": "七匹（ななひき）", "meaning": "7 ekor" },
  { "word": "八匹（はっぴき）", "meaning": "8 ekor" },
  { "word": "九匹（きゅうひき）", "meaning": "9 ekor" },
  { "word": "十匹（じゅっぴき / じっぴき）", "meaning": "10 ekor" },
  { "word": "一頭（いっとう）", "meaning": "1 ekor (Hewan Besar)" },
  { "word": "二頭（にとう）", "meaning": "2 ekor" },
  { "word": "三頭（さんとう）", "meaning": "3 ekor" },
  { "word": "四頭（よんとう）", "meaning": "4 ekor" },
  { "word": "五頭（ごとう）", "meaning": "5 ekor" },
  { "word": "六頭（ろくとう）", "meaning": "6 ekor" },
  { "word": "七頭（ななとう）", "meaning": "7 ekor" },
  { "word": "八頭（はっとう）", "meaning": "8 ekor" },
  { "word": "九頭（きゅうとう）", "meaning": "9 ekor" },
  { "word": "十頭（じゅっとう / じっとう）", "meaning": "10 ekor" },
  { "word": "一羽（いちわ）", "meaning": "1 ekor (Burung/Kelinci)" },
  { "word": "二羽（にわ）", "meaning": "2 ekor" },
  { "word": "三羽（さんわ）", "meaning": "3 ekor" },
  { "word": "四羽（よんわ）", "meaning": "4 ekor" },
  { "word": "五羽（ごわ）", "meaning": "5 ekor" },
  { "word": "六羽（ろくわ）", "meaning": "6 ekor" },
  { "word": "七羽（ななわ）", "meaning": "7 ekor" },
  { "word": "八羽（はちわ）", "meaning": "8 ekor" },
  { "word": "九羽（きゅうわ）", "meaning": "9 ekor" },
  { "word": "十羽（じゅうわ）", "meaning": "10 ekor" },
  { "word": "一階（いっかい）", "meaning": "Lantai 1" },
  { "word": "二階（にかい）", "meaning": "Lantai 2" },
  { "word": "三階（さんがい）", "meaning": "Lantai 3" },
  { "word": "四階（よんかい）", "meaning": "Lantai 4" },
  { "word": "五階（ごかい）", "meaning": "Lantai 5" },
  { "word": "六階（ろっかい）", "meaning": "Lantai 6" },
  { "word": "七階（ななかい）", "meaning": "Lantai 7" },
  { "word": "八階（はっかい）", "meaning": "Lantai 8" },
  { "word": "九階（きゅうかい）", "meaning": "Lantai 9" },
  { "word": "十階（じゅっかい / じっかい）", "meaning": "Lantai 10" }
      ],
	"Hari": [
         { "word": "月曜日（げつようび）", "meaning": "Senin" },
		  { "word": "火曜日（かようび）", "meaning": "Selasa" },
		  { "word": "水曜日（すいようび）", "meaning": "Rabu" },
		  { "word": "木曜日（もくようび）", "meaning": "Kamis" },
		  { "word": "金曜日（きんようび）", "meaning": "Jumat" },
		  { "word": "土曜日（どようび）", "meaning": "Sabtu" },
		  { "word": "日曜日（にちようび）", "meaning": "Minggu" }
      ],
	"Bulan": [
        { "word": "一月（いちがつ）", "meaning": "Januari" },
	    { "word": "二月（にがつ）", "meaning": "Februari" },
	    { "word": "三月（さんがつ）", "meaning": "Maret" },
	    { "word": "四月（しがつ）", "meaning": "April" },
	    { "word": "五月（ごがつ）", "meaning": "Mei" },
	    { "word": "六月（ろくがつ）", "meaning": "Juni" },
	    { "word": "七月（しちがつ）", "meaning": "Juli" },
	    { "word": "八月（はちがつ）", "meaning": "Agustus" },
	    { "word": "九月（くがつ）", "meaning": "September" },
	    { "word": "十月（じゅうがつ）", "meaning": "Oktober" },
	    { "word": "十一月（じゅういちがつ）", "meaning": "November" },
	    { "word": "十二月（じゅうにがつ）", "meaning": "Desember" }
      ],
	  "Tanggal": [
        { "word":" 一日（ついたち）", "meaning": "Tanggal 1" },
		{ "word": "二日（ふつか）", "meaning": "Tanggal 2" },
  { "word": "三日（みっか）", "meaning": "Tanggal 3" },
  { "word": "四日（よっか）", "meaning": "Tanggal 4" },
  { "word": "五日（いつか）", "meaning": "Tanggal 5" },
  { "word": "六日（むいか）", "meaning": "Tanggal 6" },
  { "word": "七日（なのか）", "meaning": "Tanggal 7" },
  { "word": "八日（ようか）", "meaning": "Tanggal 8" },
  { "word": "九日（ここのか）", "meaning": "Tanggal 9" },
  { "word": "十日（とおか）", "meaning": "Tanggal 10" },
  { "word": "十一日（じゅういちにち）", "meaning": "Tanggal 11" },
  { "word": "十二日（じゅうににち）", "meaning": "Tanggal 12" },
  { "word": "十三日（じゅうさんにち）", "meaning": "Tanggal 13" },
  { "word": "十四日（じゅうよっか）", "meaning": "Tanggal 14" },
  { "word": "十五日（じゅうごにち）", "meaning": "Tanggal 15" },
  { "word": "十六日（じゅうろくにち）", "meaning": "Tanggal 16" },
  { "word": "十七日（じゅうしちにち / じゅうななにち）", "meaning": "Tanggal 17" },
  { "word": "十八日（じゅうはちにち）", "meaning": "Tanggal 18" },
  { "word": "十九日（じゅうくにち）", "meaning": "Tanggal 19" },
  { "word": "二十日（はつか）", "meaning": "Tanggal 20" },
  { "word": "二十一日（にじゅういちにち）", "meaning": "Tanggal 21" },
  { "word": "二十二日（にじゅうににち）", "meaning": "Tanggal 22" },
  { "word": "二十三日（にじゅうさんにち）", "meaning": "Tanggal 23" },
  { "word": "二十四日（にじゅうよっか）", "meaning": "Tanggal 24" },
  { "word": "二十五日（にじゅうごにち）", "meaning": "Tanggal 25" },
  { "word": "二十六日（にじゅうろくにち）", "meaning": "Tanggal 26" },
  { "word": "二十七日（にじゅうしちにち / にじゅうななにち）", "meaning": "Tanggal 27" },
  { "word": "二十八日（にじゅうはちにち）", "meaning": "Tanggal 28" },
  { "word": "二十九日（にじゅうくにち）", "meaning": "Tanggal 29" },
  { "word": "三十日（さんじゅうにち）", "meaning": "Tanggal 30" },
  { "word": "三十一日（さんじゅういちにち）", "meaning": "Tanggal 31" }
      ],
	  "Waktu": [
        { "word": "一時（いちじ）", "meaning": "Jam 1" },
	  { "word": "二時（にじ）", "meaning": "Jam 2" },
	  { "word": "三時（さんじ）", "meaning": "Jam 3" },
	  { "word": "四時（よじ）", "meaning": "Jam 4" },
	  { "word": "五時（ごじ）", "meaning": "Jam 5" },
	  { "word": "六時（ろくじ）", "meaning": "Jam 6" },
	  { "word": "七時（しちじ / ななじ）", "meaning": "Jam 7" },
	  { "word": "八時（はちじ）", "meaning": "Jam 8" },
	  { "word": "九時（くじ）", "meaning": "Jam 9" },
	  { "word": "十時（じゅうじ）", "meaning": "Jam 10" },
	  { "word": "十一時（じゅういちじ）", "meaning": "Jam 11" },
	  { "word": "十二時（じゅうにじ）", "meaning": "Jam 12" },
	  { "word": "一分（いっぷん）", "meaning": "1 menit" },
	  { "word": "二分（にふん）", "meaning": "2 menit" },
	  { "word": "三分（さんぷん）", "meaning": "3 menit" },
	  { "word": "四分（よんぷん）", "meaning": "4 menit" },
	  { "word": "五分（ごふん）", "meaning": "5 menit" },
	  { "word": "六分（ろっぷん）", "meaning": "6 menit" },
	  { "word": "七分（ななふん）", "meaning": "7 menit" },
	  { "word": "八分（はっぷん / はちふん）", "meaning": "8 menit" },
	  { "word": "九分（きゅうふん）", "meaning": "9 menit" },
	  { "word": "十分（じゅっぷん / じっぷん）", "meaning": "10 menit" },
	  { "word": "三十分（さんじゅっぷん） / 半（はん）", "meaning": "30 menit / setengah jam" },
	   { "word": "きょう", "meaning": "Hari ini" },
		{ "word": "いま", "meaning": "Sekarang" },
		{ "word": "あした", "meaning": "Besok" },
		{ "word": "あさって", "meaning": "Lusa" },
		{ "word": "きのう", "meaning": "Kemarin" },
		{ "word": "おととい", "meaning": "Kemarin lusa" },
		{ "word": "こんしゅう", "meaning": "Minggu ini" },
		{ "word": "せんしゅう", "meaning": "Minggu lalu" },
		{ "word": "らいしゅう", "meaning": "Minggu depan" }
      ],
	  "Tubuh": [
        { word: "からだ", meaning: "Tubuh / Badan (Keseluruhan)" },
		{ word: "せ", meaning: "Badan (Tinggi / Pendek)" },
		{ word: "あたま", meaning: "Kepala" },
		{ word: "かみ", meaning: "Rambut" },
		{ word: "かお", meaning: "Wajah / Muka" },
		{ word: "おでこ / ひたい", meaning: "Dahi" },
		{ word: "め", meaning: "Mata" },
		{ word: "みみ", meaning: "Telinga" },
		{ word: "はな", meaning: "Hidung" },
		{ word: "ほお / ほほ", meaning: "Pipi" },
		{ word: "くち", meaning: "Mulut" },
		{ word: "くちびる", meaning: "Bibir" },
		{ word: "した", meaning: "Lidah" },
		{ word: "は", meaning: "Gigi" },
		{ word: "あご", meaning: "Dagu" },
		{ word: "ひげ", meaning: "Jenggot / Kumis" },
		{ word: "くび", meaning: "Leher" },
		{ word: "のど", meaning: "Tenggorokan" },
		{ word: "せなか", meaning: "Punggung" },
		{ word: "かた", meaning: "Bahu" },
		{ word: "うで", meaning: "Lengan" },
		{ word: "ひじ", meaning: "Siku" },
		{ word: "て", meaning: "Tangan" },
		{ word: "ゆび", meaning: "Jari" },
		{ word: "つめ", meaning: "Kuku" },
		{ word: "むね", meaning: "Dada" },
		{ word: "こし", meaning: "Pinggang" },
		{ word: "おなか", meaning: "Perut" },
		{ word: "ひざ", meaning: "Lutut" },
		{ word: "あし", meaning: "Kaki" }
      ],
      "Warna": [
        { word: "あか", meaning: "Merah" },
		{ word: "あお", meaning: "Biru" },
		{ word: "くろ", meaning: "Hitam" },
		{ word: "しろ", meaning: "Putih" },
		{ word: "きいろ", meaning: "Kuning" },
		{ word: "みどり", meaning: "Hijau" },
		{ word: "むらさき", meaning: "Ungu" },
		{ word: "ちゃいろ", meaning: "Coklat" },
		{ word: "はいいろ", meaning: "Abu-abu" },
		{ word: "ももいろ", meaning: "Merah Muda (Pink)" },
		{ word: "だいだいいろ", meaning: "Oranye" },
		{ word: "オレンジ", meaning: "Oranye" },
		{ word: "きんいろ", meaning: "Emas" },
		{ word: "ぎんいろ", meaning: "Perak" }
      ],
	  "Rasa": [
        { word: "うまみ", meaning: "Rasa Gurih" },
		{ word: "うまい", meaning: "Enak" },
		{ word: "おいしい", meaning: "Enak/Sedap" },
		{ word: "まずい", meaning: "Tidak Enak" },
		{ word: "あまみ", meaning: "Rasa Manis" },
		{ word: "あまい", meaning: "Manis" },
		{ word: "しおけ", meaning: "Rasa Asin" },
		{ word: "しょっぱい", meaning: "Asin" },
		{ word: "にがみ", meaning: "Rasa Pahit" },
		{ word: "にがい", meaning: "Pahit" },
		{ word: "からい", meaning: "Pedas" },
		{ word: "こい", meaning: "Rasa Pekat/Kental" },
		{ word: "うすい", meaning: "Rasa Tawar" }
      ],
	  "Ruang Kelas": [
        { word: "きょうしつ", meaning: "Ruang Kelas" },
		{ word: "クラス", meaning: "Kelas" },
		{ word: "じゅぎょう", meaning: "Pelajaran" },
		{ word: "きゅうけい", meaning: "Istirahat" },
		{ word: "クラスメイト", meaning: "Teman Kelas" },
		{ word: "しゃちょう", meaning: "Direktur Utama" },
		{ word: "きょうし", meaning: "Guru (Profesi)" },
		{ word: "せんせい", meaning: "Guru" },
		{ word: "がくせい", meaning: "Pelajar" },
		{ word: "せんぱい", meaning: "Senior" },
		{ word: "こうはい", meaning: "Junior" },
		{ word: "ともだち", meaning: "Teman" },
		{ word: "ドア", meaning: "Pintu" },
		{ word: "まど", meaning: "Jendela" },
		{ word: "エアコン", meaning: "AC" },
		{ word: "せんぷうき", meaning: "Kipas Angin" },
		{ word: "でんき", meaning: "Listrik / Lampu" },
		{ word: "スピーカー", meaning: "Speaker" },
		{ word: "つくえ", meaning: "Meja" },
		{ word: "てぶる", meaning: "Meja Makan" },
		{ word: "いす", meaning: "Kursi" },
		{ word: "カレンダー", meaning: "Kalender" },
		{ word: "とけい", meaning: "Jam" },
		{ word: "こくばん", meaning: "Papan Tulis Hitam" },
		{ word: "ホワイトボード", meaning: "Papan Tulis Putih (Whiteboard)" },
		{ word: "こくばんけし", meaning: "Penghapus Papan Tulis" },
		{ word: "マーカー", meaning: "Spidol" },
		{ word: "パソコン", meaning: "Laptop" },
		{ word: "きょうかしょ", meaning: "Buku Pelajaran" },
		{ word: "じしょ", meaning: "Kamus" },
		{ word: "ほん", meaning: "Buku" },
		{ word: "ノート", meaning: "Buku Catatan" },
		{ word: "てちょう", meaning: "Buku Agenda / Catatan Kecil" },
		{ word: "ペン", meaning: "Pulpen" },
		{ word: "えんぴつ", meaning: "Pensil" },
		{ word: "シャプペンシル", meaning: "Pensil Mekanik" },
		{ word: "けしゴム", meaning: "Penghapus" },
		{ word: "しゅせいえき", meaning: "Tipe-X (Penghapus Tinta)" },
		{ word: "かばん", meaning: "Tas" },
		{ word: "くつ", meaning: "Sepatu" },
		{ word: "くつした", meaning: "Kaos Kaki" },
		{ word: "スマホ", meaning: "Smartphone" }
      ],
      "Dapur": [
        { word: "だいどころ", meaning: "Dapur" },
		{ word: "キッチン", meaning: "Dapur" },
		{ word: "ガスレンジ", meaning: "Kompor Gas" },
		{ word: "フライパン", meaning: "Penggorengan / Wajan" },
		{ word: "なべ", meaning: "Panci" },
		{ word: "ヘラ", meaning: "Spatula" },
		{ word: "おたま", meaning: "Centong Sayur" },
		{ word: "やかん", meaning: "Ceret / Ketel" },
		{ word: "ほうちょう", meaning: "Pisau Dapur" },
		{ word: "まないた", meaning: "Talenan" },
		{ word: "ふきん", meaning: "Lap Dapur" },
		{ word: "ざる", meaning: "Saringan" },
		{ word: "しょっき", meaning: "Perabot Makan" },
		{ word: "さら", meaning: "Piring" },
		{ word: "コップ", meaning: "Gelas / Cangkir" },
		{ word: "ガラス", meaning: "Gelas" },
		{ word: "カップ", meaning: "Cangkir" },
		{ word: "スプーン", meaning: "Sendok" },
		{ word: "はし", meaning: "Sumpit" },
		{ word: "フォーク", meaning: "Garpu" },
		{ word: "ナイフ", meaning: "Pisau" },
		{ word: "れいぞうこ", meaning: "Kulkas" },
		{ word: "すいはんき", meaning: "Rice Cooker / Penanak Nasi" },
		{ word: "でんしレンジ", meaning: "Microwave" },
		{ word: "オーブン", meaning: "Oven" },
		{ word: "すいどう", meaning: "Saluran air keran" },
		{ word: "じゃぐち", meaning: "Keran" }
      ],
	  "Kata Kerja": [
{ "word": "<span style='color:red'>[1]</span> 飲む, のむ, のみます", "meaning": "Minum" },
{ "word": "<span style='color:red'>[2]</span> 食べる, たべる, たべます", "meaning": "Makan" },
{ "word": "<span style='color:red'>[3]</span> する, します", "meaning": "Melakukan / melakukan" },
{ "word": "<span style='color:red'>[2]</span> 見る, みる, みます", "meaning": "Melihat" },
{ "word": "<span style='color:red'>[1]</span> 帰る, かえる, かえります", "meaning": "Pulang" },
{ "word": "<span style='color:red'>[1]</span> 行く, いく, いきます", "meaning": "Pergi ke" },
{ "word": "<span style='color:red'>[3]</span> 来る, くる, きます", "meaning": "Datang" },
{ "word": "<span style='color:red'>[3]</span> スキーをする, スキーをします", "meaning": "Bermain ski" },
{ "word": "<span style='color:red'>[1]</span> 読む, よむ, よみます", "meaning": "Membaca" },
{ "word": "<span style='color:red'>[3]</span> 勉強する, べんきょうする, べんきょうします", "meaning": "Belajar" },
{ "word": "<span style='color:red'>[1]</span> 聞く, きく, ききます", "meaning": "Mendengar / Bertanya" },
{ "word": "<span style='color:red'>[1]</span> 買う, かう, かいます", "meaning": "Membeli" },
{ "word": "<span style='color:red'>[2]</span> 寝る, ねる, ねます", "meaning": "Tidur" },
{ "word": "<span style='color:red'>[2]</span> 起きる, おきる, おきます", "meaning": "Bangun (dari tidur)" },
{ "word": "<span style='color:red'>[1]</span> 働く, はたらく, はたらきます", "meaning": "Bekerja" },
{ "word": "<span style='color:red'>[1]</span> 歩く, あるく, あるきます", "meaning": "Berjalan kaki" },
{ "word": "<span style='color:red'>[1]</span> ある, あります", "meaning": "Ada (untuk benda mati)" },
{ "word": "<span style='color:red'>[1]</span> 会う, あう, あいます", "meaning": "Bertemu" },
{ "word": "<span style='color:red'>[3]</span> 買い物する, かいものする, かいものします", "meaning": "Berbelanja" },
{ "word": "<span style='color:red'>[3]</span> 洗濯する, せんたくする, せんたくします", "meaning": "Mencuci (pakaian)" },
{ "word": "<span style='color:red'>[3]</span> 掃除する, そうじする, そうじします", "meaning": "Membersihkan" },
{ "word": "<span style='color:red'>[1]</span> 作る, つくる, つくります", "meaning": "Membuat" },
{ "word": "<span style='color:red'>[3]</span> 食事する, しょくじする, しょくじします", "meaning": "Makan / melakukan makan" },
{ "word": "<span style='color:red'>[1]</span> 登る, のぼる, のぼります", "meaning": "Mendaki (ke tempat tinggi)" },
{ "word": "<span style='color:red'>[1]</span> 入る, はいる, はいります", "meaning": "Masuk ke〜" },
{ "word": "<span style='color:red'>[1]</span> 撮る, とる, とります", "meaning": "Mengambil (foto)" },
{ "word": "<span style='color:red'>[2]</span> 借りる, かりる, かります", "meaning": "Meminjam" },
{ "word": "<span style='color:red'>[1]</span> 遊ぶ, あそぶ, あそびます", "meaning": "Bermain" },
{ "word": "<span style='color:red'>[2]</span> 開ける, あける, あけます", "meaning": "Membuka" },
{ "word": "<span style='color:red'>[2]</span> 閉める, しめる, しめます", "meaning": "Menutup" },
{ "word": "<span style='color:red'>[1]</span> 持つ, もつ, もちます", "meaning": "Membawa" },
{ "word": "<span style='color:red'>[3]</span> 持ってくる, もってくる, もってきます", "meaning": "Membawa ke sini" },
{ "word": "<span style='color:red'>[1]</span> 吸う, すう, すいます", "meaning": "Menghirup / Merokok" },
{ "word": "<span style='color:red'>[1]</span> 歌う, うたう, うたいます", "meaning": "Menyanyi" },
{ "word": "<span style='color:red'>[1]</span> 弾く, ひく, ひきます", "meaning": "Memainkan (alat musik)" },
{ "word": "<span style='color:red'>[2]</span> かける, かけます", "meaning": "Menelepon" },
{ "word": "<span style='color:red'>[1]</span> 話す, はなす, はなします", "meaning": "Berbicara" },
{ "word": "<span style='color:red'>[2]</span> 教える, おしえる, おしえます", "meaning": "Mengajarkan / Memberi tahu" },
{ "word": "<span style='color:red'>[1]</span> 切る, きる, きります", "meaning": "Memotong" },
{ "word": "<span style='color:red'>[1]</span> 手伝う, てつだう, てつだいます", "meaning": "Membantu" },
{ "word": "<span style='color:red'>[1]</span> 洗う, あらう, あらいます", "meaning": "Mencuci" },
{ "word": "<span style='color:red'>[1]</span> 書く, かく, かきます", "meaning": "Menulis" },
{ "word": "<span style='color:red'>[2]</span> 入れる, いれる, いれます", "meaning": "Memasukkan" },
{ "word": "<span style='color:red'>[1]</span> 出す, だす, だします", "meaning": "Mengeluarkan" },
{ "word": "<span style='color:red'>[1]</span> 貸す, かす, かします", "meaning": "Meminjamkan" },
{ "word": "<span style='color:red'>[1]</span> 取る, とる, とります", "meaning": "Mengambil" },
{ "word": "<span style='color:red'>[1]</span> 置く, おく, おきます", "meaning": "Meletakkan" },
{ "word": "<span style='color:red'>[1]</span> 使う, つかう, つかいます", "meaning": "Menggunakan" },
{ "word": "<span style='color:red'>[1]</span> 持って行く, もっていく, もっていきます", "meaning": "Membawa pergi" },
{ "word": "<span style='color:red'>[1]</span> 死ぬ, しぬ, しにます", "meaning": "Mati" },
{ "word": "<span style='color:red'>[1]</span> 住む, すむ, すみます", "meaning": "Tinggal" },
{ "word": "<span style='color:red'>[2]</span> いる, います", "meaning": "Ada (makhluk hidup)" },
{ "word": "<span style='color:red'>[3]</span> 電話をする, でんわをする, でんわをします", "meaning": "Menelepon" },
{ "word": "<span style='color:red'>[1]</span> 送る, おくる, おくります", "meaning": "Mengirim" },
{ "word": "<span style='color:red'>[2]</span> あげる, あげます", "meaning": "Memberi (kepada orang lain)" },
{ "word": "<span style='color:red'>[1]</span> もらう, もらいます", "meaning": "Menerima" },
{ "word": "<span style='color:red'>[2]</span> くれる, くれます", "meaning": "Memberi (kepada saya)" },
{ "word": "<span style='color:red'>[2]</span> できる, できます", "meaning": "Bisa" },
{ "word": "<span style='color:red'>[3]</span> 参加する, さんかする, さんかします", "meaning": "Ikut serta dalam〜" },
{ "word": "<span style='color:red'>[1]</span> 習う, ならう, ならいます", "meaning": "Belajar〜" },
{ "word": "<span style='color:red'>[1]</span> 乗る, のる, のります", "meaning": "Naik〜" },
{ "word": "<span style='color:red'>[1]</span> 申し込む, もうしこむ, もうしこみます", "meaning": "Mendaftar" },
{ "word": "<span style='color:red'>[1]</span> 絵をかく, えをかく, えをかきます", "meaning": "Melukis / Menggambar" },
{ "word": "<span style='color:red'>[1]</span> 泳ぐ, およぐ, およぎます", "meaning": "Berenang" },
{ "word": "<span style='color:red'>[1]</span> 言う, いう, いいます", "meaning": "Mengatakan" },
{ "word": "<span style='color:red'>[1]</span> 払う, はらう, はらいます", "meaning": "Membayar" },
{ "word": "<span style='color:red'>[2]</span> 降りる, おりる, おります", "meaning": "Turun dari〜" },
{ "word": "<span style='color:red'>[2]</span> 見せる, みせる, みせます", "meaning": "Memperlihatkan" },
{ "word": "<span style='color:red'>[3]</span> 予約する, よやくする, よやくします", "meaning": "Memesan / Reservasi" },
{ "word": "<span style='color:red'>[3]</span> 運転する, うんてんする, うんてんします", "meaning": "Menyetir" },
{ "word": "<span style='color:red'>[2]</span> 集める, あつめる, あつめます", "meaning": "Mengumpulkan" },
{ "word": "<span style='color:red'>[1]</span> 探す, さがす, さがします", "meaning": "Mencari" },
{ "word": "<span style='color:red'>[2]</span> 見える, みえる, みえます", "meaning": "Terlihat" },
{ "word": "<span style='color:red'>[2]</span> 聞こえる, きこえる, きこえます", "meaning": "Terdengar" },
{ "word": "<span style='color:red'>[1]</span> 渡る, わたる, わたります", "meaning": "Menyeberang" },
{ "word": "<span style='color:red'>[1]</span> 曲がる, まがる, まがります", "meaning": "Belok" },
{ "word": "<span style='color:red'>[1]</span> 座る, すわる, すわります", "meaning": "Duduk di" },
{ "word": "<span style='color:red'>[1]</span> 押す, おす, おします", "meaning": "Mendorong" },
{ "word": "<span style='color:red'>[1]</span> 立つ, たつ, たちます", "meaning": "Berdiri" },
{ "word": "<span style='color:red'>[1]</span> なくす, なくします", "meaning": "Kehilangan" },
{ "word": "<span style='color:red'>[2]</span> 遅れる, おくれる, おくれます", "meaning": "Terlambat" },
{ "word": "<span style='color:red'>[3]</span> 集合する, しゅうごうする, しゅうごうします", "meaning": "Berkumpul (bentuk sopan)" },
{ "word": "<span style='color:red'>[1]</span> 持って帰る, もってかえる, もってかえります", "meaning": "Membawa pulang" },
{ "word": "<span style='color:red'>[1]</span> 飛ぶ, とぶ, とびます", "meaning": "Terbang" },
{ "word": "<span style='color:red'>[1]</span> 歩く, あるく, あるきます", "meaning": "Berjalan kaki" },
{ "word": "<span style='color:red'>[1]</span> 休む, やすむ, やすみます", "meaning": "Istirahat" },
{ "word": "<span style='color:red'>[1]</span> お腹がすく, おなかがすく, おなかがすきます", "meaning": "Lapar" },
{ "word": "<span style='color:red'>[1]</span> 喉が渇く, のどがかわく, のどがかわきます", "meaning": "Haus" },
{ "word": "<span style='color:red'>[2]</span> 疲れる, つかれる, つかれます", "meaning": "Lelah" },
{ "word": "<span style='color:red'>[1]</span> やる, やります", "meaning": "Melakukan (bentuk informal)" },
{ "word": "<span style='color:red'>[1]</span> なる, なります", "meaning": "Menjadi" },
{ "word": "<span style='color:red'>[2]</span> 慣れる, なれる, なれます", "meaning": "Terbiasa" },
{ "word": "<span style='color:red'>[1]</span> 終わる, おわる, おわります", "meaning": "Selesai" },
{ "word": "<span style='color:red'>[1]</span> 通う, かよう, かよいます", "meaning": "Pergi (rutin)" },
{ "word": "<span style='color:red'>[3]</span> 散歩する, さんぽする, さんぽします", "meaning": "Jalan-jalan" },
{ "word": "<span style='color:red'>[1]</span> 風をひく, かぜをひく, かぜをひきます", "meaning": "Masuk angin" },
{ "word": "<span style='color:red'>[1]</span> 学校を休む, がっこうをやすむ, がっこうをやすみます", "meaning": "Tidak masuk sekolah" },
{ "word": "<span style='color:red'>[2]</span> 忘れる, わすれる, わすれます", "meaning": "Lupa" },
{ "word": "<span style='color:red'>[3]</span> 卒業する, そつぎょうする, そつぎょうします", "meaning": "Lulus" },
{ "word": "<span style='color:red'>[3]</span> 入学する, にゅうがくする, にゅうがくします", "meaning": "Masuk sekolah/perguruan tinggi" },
{ "word": "<span style='color:red'>[2]</span> 別れる, わかれる, わかれます", "meaning": "Berpisah" },
{ "word": "<span style='color:red'>[2]</span> 始める, はじめる, はじめます", "meaning": "Memulai" },
{ "word": "<span style='color:red'>[1]</span> 消す, けす, けします", "meaning": "Mematikan (alat listrik)" },
{ "word": "<span style='color:red'>[2]</span> つける, つけます", "meaning": "Menyalakan" },
{ "word": "<span style='color:red'>[3]</span> 引っ越しする, ひっこしする, ひっこしします", "meaning": "Pindah rumah" },
{ "word": "<span style='color:red'>[1]</span> 治る, なおる, なおります", "meaning": "Sembuh" },
{ "word": "<span style='color:red'>[1]</span> 塗る, ぬる, ぬります", "meaning": "Mengoleskan (salep)" },
{ "word": "<span style='color:red'>[2]</span> 浴びる, あびる, あびます", "meaning": "Mandi / Disiram" },
{ "word": "<span style='color:red'>[3]</span> 声を出す, こえをだす, こえをだします", "meaning": "Mengeluarkan suara" },
{ "word": "<span style='color:red'>[1]</span> 磨く, みがく, みがきます", "meaning": "Menggosok (gigi)" },
{ "word": "<span style='color:red'>[1]</span> 待つ, まつ, まちます", "meaning": "Menunggu" },
{ "word": "<span style='color:red'>[3]</span> 準備する, じゅんびする, じゅんびします", "meaning": "Mempersiapkan" },
{ "word": "<span style='color:red'>[1]</span> 脱ぐ, ぬぐ, ぬぎます", "meaning": "Melepas (pakaian)" },
{ "word": "<span style='color:red'>[1]</span> 知る, しる, しります", "meaning": "Mengetahui / Tahu" },
{ "word": "<span style='color:red'>[3]</span> デートする, デートする, デートします", "meaning": "Berkencan" },
{ "word": "<span style='color:red'>[1]</span> 売る, うる, うります", "meaning": "Menjual" },
{ "word": "<span style='color:red'>[1]</span> 泊まる, とまる, とまります", "meaning": "Menginap" },
{ "word": "<span style='color:red'>[3]</span> 練習する, れんしゅうする, れんしゅうします", "meaning": "Berlatih" },
{ "word": "<span style='color:red'>[1]</span> 触る, さわる, さわります", "meaning": "Menyentuh" },
{ "word": "<span style='color:red'>[1]</span> 開く, あく, あきます", "meaning": "Terbuka (otomatis)" },
{ "word": "<span style='color:red'>[1]</span> つく, つく, つきます", "meaning": "Menyala" },
{ "word": "<span style='color:red'>[1]</span> 回す, まわす, まわします", "meaning": "Memutar" },
{ "word": "<span style='color:red'>[2]</span> 出る, でる, でます", "meaning": "Keluar" },
{ "word": "<span style='color:red'>[2]</span> 止める, とめる, とめます", "meaning": "Menghentikan" },
{ "word": "<span style='color:red'>[1]</span> 並ぶ, ならぶ, ならびます", "meaning": "Berbaris" },
{ "word": "<span style='color:red'>[2]</span> 分ける, わける, わけます", "meaning": "Membagi / Memisahkan" },
{ "word": "<span style='color:red'>[3]</span> 経験する, けいけんする, けいけんします", "meaning": "Mengalami" },
{ "word": "<span style='color:red'>[3]</span> 化粧する, けしょうする, けしょうします", "meaning": "Berdandan / Merias wajah" },
{ "word": "<span style='color:red'>[2]</span> 負ける, まける, まけます", "meaning": "Kalah (dari)" },
{ "word": "<span style='color:red'>[1]</span> 勝つ, かつ, かちます", "meaning": "Menang (atas)" },
{ "word": "<span style='color:red'>[1]</span> 降る, ふる, ふります", "meaning": "Turun (hujan/salju)" },
{ "word": "<span style='color:red'>[2]</span> 倒れる, たおれる, たおれます", "meaning": "Tumbang, roboh" },
{ "word": "<span style='color:red'>[1]</span> 止まる, とまる, とまります", "meaning": "Berhenti" },
{ "word": "<span style='color:red'>[1]</span> 亡くなる, なくなる, なくなります", "meaning": "Wafat" },
{ "word": "<span style='color:red'>[2]</span> 割れる, われる, われます", "meaning": "Pecah" },
{ "word": "<span style='color:red'>[2]</span> 晴れる, はれる, はれます", "meaning": "Cerah" },
{ "word": "<span style='color:red'>[1]</span> やむ, やむ, やみます", "meaning": "Berhenti (hujan/salju)" },
{ "word": "<span style='color:red'>[1]</span> 急ぐ, いそぐ, いそぎます", "meaning": "Bergegas, buru-buru" },
{ "word": "<span style='color:red'>[1]</span> 間に合う, まにあう, まにあいます", "meaning": "Tepat waktu, sempat" },
{ "word": "<span style='color:red'>[1]</span> 集まる, あつまる, あつまります", "meaning": "Berkumpul" },
{ "word": "<span style='color:red'>[1]</span> 閉まる, しまる, しまります", "meaning": "Tertutup" },
{ "word": "<span style='color:red'>[2]</span> 落ちる, おちる, おちます", "meaning": "Jatuh" },
{ "word": "<span style='color:red'>[2]</span> 消える, きえる, きえます", "meaning": "Padam, hilang" },
{ "word": "<span style='color:red'>[2]</span> 壊れる, こわれる, こわれます", "meaning": "Rusak" },
{ "word": "<span style='color:red'>[2]</span> 汚れる, よごれる, よごれます", "meaning": "Kotor" }


      ],
	    "Kata Sifat-i": [
	     { "word": "新しい（あたらしい）", "meaning": "Baru" },
  { "word": "古い（ふるい）", "meaning": "Lama / tua (benda)" },
  { "word": "大きい（おおきい）", "meaning": "Besar" },
  { "word": "小さい（ちいさい）", "meaning": "Kecil" },
  { "word": "高い（たかい）", "meaning": "Tinggi / mahal" },
  { "word": "低い（ひくい）", "meaning": "Rendah" },
  { "word": "多い（おおい）", "meaning": "Banyak" },
  { "word": "少ない（すくない）", "meaning": "Sedikit" },
  { "word": "暑い（あつい）", "meaning": "Panas (cuaca)" },
  { "word": "寒い（さむい）", "meaning": "Dingin (cuaca)" },
  { "word": "暖かい（あたたかい）", "meaning": "Hangat" },
  { "word": "涼しい（すずしい）", "meaning": "Sejuk" },
  { "word": "熱い（あつい）", "meaning": "Panas (untuk benda/minuman)" },
  { "word": "冷たい（つめたい）", "meaning": "Dingin (untuk benda/minuman)" },
  { "word": "おいしい", "meaning": "Enak / Lezat" },
  { "word": "甘い（あまい）", "meaning": "Manis" },
  { "word": "辛い（からい）", "meaning": "Pedas" },
  { "word": "苦い（にがい）", "meaning": "Pahit" },
  { "word": "すっぱい", "meaning": "Asam" },
  { "word": "楽しい（たのしい）", "meaning": "Menyenangkan / seru" },
  { "word": "忙しい（いそがしい）", "meaning": "Sibuk" },
  { "word": "難しい（むずかしい）", "meaning": "Sulit / susah" },
  { "word": "近い（ちかい）", "meaning": "Dekat" },
  { "word": "遠い（とおい）", "meaning": "Jauh" },
  { "word": "早い（はやい）", "meaning": "Cepat / Awal" },
  { "word": "広い（ひろい）", "meaning": "Luas" },
  { "word": "少し（すこし）", "meaning": "Sedikit" },
  { "word": "かわいい", "meaning": "Lucu / imut" },
  { "word": "かっこいい", "meaning": "Keren" },
  { "word": "背が低い（せがひくい）", "meaning": "Bertubuh pendek" },
  { "word": "背が高い（せがたかい）", "meaning": "Bertubuh tinggi" },
  { "word": "短い（みじかい）", "meaning": "Pendek" },
  { "word": "長い（ながい）", "meaning": "Panjang" },
  { "word": "茶色い（ちゃいろい）", "meaning": "Cokelat" },
  { "word": "白い（しろい）", "meaning": "Putih" },
  { "word": "黒い（くろい）", "meaning": "Hitam" },
  { "word": "優しい（やさしい）", "meaning": "Baik hati / ramah" },
  { "word": "すごい", "meaning": "Hebat" },
  { "word": "痛い（いたい）", "meaning": "Sakit (rasa sakit)" },
  { "word": "暗い（くらい）", "meaning": "Gelap" },
  { "word": "寂しい（さびしい）", "meaning": "Kesepian" },
   { "word": "悪い（わるい）", "meaning": "Buruk / Jelek" },
  { "word": "気持ちが悪い（きもちがわるい）", "meaning": "Merasa tidak enak / mual" },
  { "word": "固い（かたい）", "meaning": "Keras" },
  { "word": "柔らかい（やわらかい）", "meaning": "Lunak / Lembut" },
  { "word": "若い（わかい）", "meaning": "Muda" },
  { "word": "青い（あおい）", "meaning": "Biru" },
  { "word": "赤い（あかい）", "meaning": "Merah" },
  { "word": "黄色い（きいろい）", "meaning": "Kuning" },
  { "word": "怖い（こわい）", "meaning": "Menakutkan" },
  { "word": "うるさい（うるさい）", "meaning": "Berisik" },
  { "word": "強い（つよい）", "meaning": "Kuat" }
		  ],
		    "Kata Sifat-na": [
	    { "word": "静か（しずか）", "meaning": "Tenang" },
	   { "word": "にぎやか", "meaning": "Ramai" },
	   { "word": "きれい", "meaning": "Indah / bersih / cantik" },
	   { "word": "有名（ゆうめい）", "meaning": "Terkenal" },
	   { "word": "ひま", "meaning": "Senggang / waktu luang" },
	   { "word": "大変（たいへん）", "meaning": "Berat / sulit / parah" },
	   { "word": "簡単（かんたん）", "meaning": "Mudah / gampang" },
	   { "word": "好き（すき）", "meaning": "Suka" },
	   { "word": "嫌い（きらい）", "meaning": "Tidak suka / benci" },
	   { "word": "残念（ざんねん）", "meaning": "Sayang sekali / menyesal" },
	   { "word": "まじめ", "meaning": "Serius / rajin" },
	   { "word": "親切（しんせつ）", "meaning": "Baik hati / ramah" },
	   { "word": "元気（げんき）", "meaning": "Sehat / semangat" },
	   { "word": "いろいろ", "meaning": "Berbagai macam" },
	   { "word": "大切（たいせつ）", "meaning": "Penting" },
	   { "word": "迷惑（めいわく）", "meaning": "Gangguan / merepotkan" },
	     { "word": "大丈夫（だいじょうぶ）", "meaning": "Tidak apa-apa / Baik saja" },
  { "word": "新鮮（しんせん）", "meaning": "Segar" },
  { "word": "人気（にんき）", "meaning": "Populer" },
  { "word": "便利（べんり）", "meaning": "Praktis / Nyaman" },
  { "word": "複雑（ふくざつ）", "meaning": "Rumit / Kompleks" },
  { "word": "おしゃれ（おしゃれ）", "meaning": "Modis / Bergaya" },
  { "word": "自由（じゆう）", "meaning": "Bebas" },
  { "word": "不便（ふべん）", "meaning": "Tidak praktis / Tidak nyaman" },
  { "word": "心配（しんぱい）", "meaning": "Khawatir" },
  { "word": "本当（ほんとう）", "meaning": "Benar-benar" }
		  ],
	   "Lesson 1": [
	   { word: "にほん (Nihon)", meaning: "Jepang" },
	   { word: "アメリカ (Amerika)", meaning: "Amerika" },
	   { word: "イタリア (Itaria)", meaning: "Italia" },
	   { word: "オーストラリア (Ōsutoria)", meaning: "Australia" },
	   { word: "かんこく (Kankoku)", meaning: "Korea" },
	   { word: "ちゅうごく (Chūgoku)", meaning: "Cina / Tiongkok" },
	   { word: "タイ (Tai)", meaning: "Thailand" },
	   { word: "ロシア (Roshia)", meaning: "Rusia" },
	   { word: "～じん (~jin)", meaning: "Orang" },
	   { word: "どちら (dochira)", meaning: "Yang mana / Di mana" },
	   { word: "国（くに）(kuni)", meaning: "Negara" },
	   { word: "お国（くに）は (okuni wa)", meaning: "Dari negara mana?" },
	   { word: "どちらですか (dochira desu ka)", meaning: "Yang mana? " },
       { word: "(お)仕事（しごと）", meaning: "(Pekerjaan) kerja" },
	   { word: "学生（がくせい）", meaning: "Siswa / Mahasiswa" },
	   { word: "先生（せんせい）", meaning: "Guru / Dosen (sapaan)" },
	   { word: "教師（きょうし）", meaning: "Guru (profesi, formal)" },
	   { word: "会社員（かいしゃいん）", meaning: "Pegawai perusahaan" },
	   { word: "社員（しゃいん）", meaning: "Pegawai perusahaan " },
	   { word: "～さん", meaning: "Tuan/Nyonya/Nona" },
	   { word: "そうですか", meaning: "Oh begitu ya?" },
	   { word: "高校（こうこう）", meaning: "SMA)" },
	   { word: "大学（だいがく）", meaning: "Universitas" },
	   { word: "日本語学校（にほんご がっこう）", meaning: "Sekolah Bahasa Jepang" },
	   { word: "誕生日（たんじょうび）", meaning: "Ulang tahun" },
	   { word: "～月（～がつ）", meaning: "Bulan " },
	   { word: "～日（～にち／か）", meaning: "Tanggal" },
	   { word: "いつ", meaning: "Kapan" },
	   { word: "趣味（しゅみ）", meaning: "Hobi" },
	   { word: "スポーツ", meaning: "Olahraga" },
	   { word: "サッカー", meaning: "Sepak bola" },
	   { word: "テニス", meaning: "Tenis" },
	   { word: "水泳（すいえい）", meaning: "Berenang" },
	   { word: "映画（えいが）", meaning: "Film" },
	   { word: "音楽（おんがく）", meaning: "Musik" },
	   { word: "読書（どくしょ）", meaning: "Membaca" },
	   { word: "旅行（りょこう）", meaning: "Jalan-jalan / Bepergian" },
	   { word: "料理（りょうり）", meaning: "Memasak" },
	   { word: "何（なん）", meaning: "Apa" }
	   ],
	  "Lesson 2": [
	  { word: "喫煙所（きつえんじょ）", meaning: "Tempat merokok" },
	  { word: "トイレ", meaning: "Toilet" },
	  { word: "喫茶店（きっさてん）", meaning: "Cafe" },
	  { word: "スーパー", meaning: "Supermarket" },
	  { word: "１００円ショップ", meaning: "Toko serba 100 yen" },
	  { word: "レストラン", meaning: "Restoran" },
	  { word: "地下（ちか）", meaning: "Lantai bawah" },
	  { word: "くつ", meaning: "Sepatu" },
	  { word: "本（ほん）", meaning: "Buku" },
	  { word: "ケーキ", meaning: "Kue" },
	  { word: "パン", meaning: "Roti" },
	  { word: "店員（てんいん）", meaning: "Pegawai toko" },
	  { word: "～階（～かい）", meaning: "Lantai" },
	  { word: "～屋（～や）", meaning: "Toko" },
	  { word: "くつ屋（くつや）", meaning: "Toko sepatu" },
	  { word: "いっかい", meaning: "Lantai 1" },
	  { word: "にかい", meaning: "Lantai 2" },
	  { word: "さんがい", meaning: "Lantai 3" },
	  { word: "よんかい", meaning: "Lantai 4" },
	  { word: "ごかい", meaning: "Lantai 5" },
	  { word: "ろっかい", meaning: "Lantai 6" },
	  { word: "ななかい", meaning: "Lantai 7" },
	  { word: "はっかい", meaning: "Lantai 8" },
	  { word: "きゅうかい", meaning: "Lantai 9" },
	  { word: "じゅっかい", meaning: "Lantai 10" },
	  { word: "なんかい", meaning: "Lantai berapa? (pertanyaan)" },
	  { word: "ここ", meaning: "Di sini" },
	  { word: "そこ", meaning: "Di situ" },
	  { word: "あそこ", meaning: "Di sana" },
	  { word: "どこ", meaning: "Di mana" },
	  { word: "インフォメーション", meaning: "Informasi" },
	  { word: "エスカレーター", meaning: "Eskalator" },
	  { word: "エレベーター", meaning: "Lift" },
	  { word: "レジ", meaning: "Kasir" },
	  { word: "ATM（エーティーエム）", meaning: "ATM" },
	  { word: "（どうも）ありがとうございます", meaning: "Terima kasih banyak" },
	  { word: "カメラ", meaning: "Kamera" },
	  { word: "携帯電話（けいたいでんわ）", meaning: "Telepon" },
	  { word: "電子辞書（でんしじしょ）", meaning: "Kamus elektronik" },
	  { word: "パソコン", meaning: "Laptop" },
	  { word: "けしゴム", meaning: "Penghapus karet" },
	  { word: "ペン", meaning: "Pena" },
	  { word: "トイレットペーパー", meaning: "Tisu toilet" },
	  { word: "油（あぶら）", meaning: "Minyak" },
	  { word: "米（こめ）", meaning: "Beras" },
	  { word: "卵（たまご）", meaning: "Telur" },
	  { word: "水（みず）", meaning: "Air" },
	  { word: "いらっしゃいませ", meaning: "Selamat datang" },
	  { word: "これ", meaning: "Ini" },
	  { word: "それ", meaning: "Itu" },
	  { word: "あれ", meaning: "Itu" },
	  { word: "～円（えん）", meaning: "Yen" },
	  { word: "いくら", meaning: "Berapa" },
	  { word: "この", meaning: "Ini" },
	  { word: "その", meaning: "Itu" },
	  { word: "あの", meaning: "Itu" },
	  { word: "Tシャツ", meaning: "Kaos / T-shirt" },
	  { word: "肉（にく）", meaning: "Daging" },
	  { word: "鶏肉（とりにく）", meaning: "Daging ayam" },
	  { word: "牛肉（ぎゅうにく）", meaning: "Daging sapi" },
	  { word: "豚肉（ぶたにく）", meaning: "Daging babi" },
	  { word: "魚（さかな）", meaning: "Ikan" },
	  { word: "スープ", meaning: "Sup" },
	  { word: "卵（たまご）", meaning: "Telur" },
	  { word: "ケーキ", meaning: "Kue" },
	  { word: "ジュース", meaning: "Jus" },
	  { word: "いちご", meaning: "Stroberi" },
	  { word: "りんご", meaning: "Apel" },
	  { word: "料理（りょうり）", meaning: "Memasak" },
	  { word: "～語（ご）", meaning: "Bahasa" },
	  { word: "英語（えいご）", meaning: "Bahasa Inggris" },
	  { word: "お茶（ちゃ）", meaning: "Teh (hijau)" },
	  { word: "紅茶（こうちゃ）", meaning: "Teh hitam" },
	  { word: "ワイン", meaning: "Anggur (minuman beralkohol)" },
	  { word: "ビール", meaning: "Bir" },
	  { word: "アメリカ", meaning: "Amerika" },
	  { word: "ドイツ", meaning: "Jerman" },
	  { word: "フランス", meaning: "Prancis" },
	  { word: "インド", meaning: "India" },
	  { word: "日本（にほん）", meaning: "Jepang" },
	  { word: "インドネシア", meaning: "Indonesia" },
	  { word: "韓国（かんこく）", meaning: "Korea Selatan" },
	  { word: "パソコン", meaning: "Komputer (PC)" },
	  { word: "ケーキ", meaning: "Kue" },
	  { word: "紅茶（こうちゃ）", meaning: "Teh hitam" },
	  { word: "カレー", meaning: "Kare (kari)" },
	  { word: "ビール", meaning: "Bir" },
	  { word: "とんかつ", meaning: "Babi goreng tepung" },
	  { word: "コーヒー", meaning: "Kopi" },
	  { word: "ハンバーグ", meaning: "Hamburger steak" },
	  { word: "ごはん／ライス", meaning: "Nasi" },
	  { word: "パン", meaning: "Roti" },
	  { word: "ジュース", meaning: "Jus" },
	  { word: "～つ", meaning: "Satuan benda (penghitung)" },
	  { word: "注文（ちゅうもん）", meaning: "Pesanan" },
	  { word: "ひとつ", meaning: "1 buah" },
	  { word: "ふたつ", meaning: "2 buah" },
	  { word: "みっつ", meaning: "3 buah" },
	  { word: "よっつ", meaning: "4 buah" },
	  { word: "いつつ", meaning: "5 buah" },
	  { word: "むっつ", meaning: "6 buah" },
	  { word: "ななつ", meaning: "7 buah" },
	  { word: "やっつ", meaning: "8 buah" },
	  { word: "ここのつ", meaning: "9 buah" },
	  { word: "とお", meaning: "10 buah" },
	  { word: "私（わたし）", meaning: "Saya" },
	  { word: "ご馳走さまでした（ごちそうさまでした）", meaning: "Terima kasih atas makanannya" },
	  { word: "鞄（かばん）", meaning: "Tas" },
	  { word: "パソコン", meaning: "Laptop / Komputer pribadi" },
	  { word: "携帯電話（けいたいでんわ）", meaning: "HP / Telepon genggam" },
	  { word: "時計（とけい）", meaning: "Jam (tangan atau dinding)" },
	  { word: "カメラ", meaning: "Kamera" }
	],
	"Lesson 3": [
	  { word: "いま", meaning: "Sekarang" },
	  { word: "～じ", meaning: "Jam" },
	  { word: "さんじ", meaning: "Jam 3" },
	  { word: "～ふん／～ぷん", meaning: "Menit" },
	  { word: "ごふん", meaning: "5 menit" },
	  { word: "～じはん", meaning: "30 menit / setengah jam" },
	  { word: "いちじはん", meaning: "Jam setengah dua (1:30)" },
	  { word: "午前（ごぜん）", meaning: "Pagi (setelah jam 12 malam)" },
	  { word: "午後（ごご）", meaning: "Siang (setelah jam 12 siang)" },
	  { word: "昼（ひる）", meaning: "Siang" },
	  { word: "銀行（ぎんこう）", meaning: "Bank" },
	  { word: "体育館（たいいくかん）", meaning: "Gedung olahraga" },
	  { word: "図書館（としょかん）", meaning: "Perpustakaan" },
	  { word: "病院（びょういん）", meaning: "Rumah sakit" },
	  { word: "郵便局（ゆうびんきょく）", meaning: "Kantor pos" },
	  { word: "授業（じゅぎょう）", meaning: "Pelajaran/kegiatan belajar" },
	  { word: "テスト", meaning: "Tes/ujian" },
	  { word: "休み（やすみ）", meaning: "Libur/istirahat" },
	  { word: "時間（じかん）", meaning: "Waktu/jam" },
	  { word: "スケジュール", meaning: "Jadwal" },
	  { word: "パーティー", meaning: "Pesta" },
	  { word: "留学生（りゅうがくせい）", meaning: "Mahasiswa asing" },
	  { word: "１年（いちねん）", meaning: "Tahun pertama" },
	  { word: "何（なに）", meaning: "Apa" },
	  { word: "飲みます（のみます）", meaning: "Minum" },
	  { word: "食べます（たべます）", meaning: "Makan" },
	  { word: "します", meaning: "Melakukan / melakukan" },
	  { word: "見ます（みます）", meaning: "Melihat / menonton" },
	  { word: "アルバイト", meaning: "Kerja paruh waktu" },
	  { word: "スキー", meaning: "Ski" },
	  { word: "バーベキュー", meaning: "Barbekyu (BBQ)" },
	  { word: "花火（はなび）", meaning: "Kembang api" },
	  { word: "お花見（はなみ）", meaning: "Melihat bunga sakura" },
	  { word: "お祭り（まつり）", meaning: "Festival / perayaan" },
	  { word: "おさけ（お酒）", meaning: "Sake" },
	  { word: "おすし（お寿司）", meaning: "Sushi" },
	  { word: "いいですね", meaning: "Bagus ya / kedengarannya bagus" },
	  { word: "ホームステイ", meaning: "Homestay" },
	  { word: "海（うみ）", meaning: "Laut" },
	  { word: "公園（こうえん）", meaning: "Taman" },
	  { word: "バス", meaning: "Bus" },
	  { word: "富士山（ふじさん）", meaning: "Gunung Fuji" },
	  { word: "帰ります（かえります）", meaning: "Pulang" },
	  { word: "行きます（いきます）", meaning: "Pergi" },
	  { word: "来ます（きます）", meaning: "Datang" },
	  { word: "春（はる）", meaning: "Musim semi" },
	  { word: "夏（なつ）", meaning: "Musim panas" },
	  { word: "秋（あき）", meaning: "Musim gugur" },
	  { word: "冬（ふゆ）", meaning: "Musim dingin" },
	  { word: "夏休み（なつやすみ）", meaning: "Liburan musim panas" },
	  { word: "～休み（やすみ）", meaning: "Libur / Istirahat" },
	  { word: "ゴールデンウィーク", meaning: "Golden Week (minggu libur panjang di Jepang)" },
	  { word: "スキーをします", meaning: "Bermain ski" },
	  { word: "北海道（ほっかいどう）", meaning: "Hokkaido (nama pulau di Jepang)" },
	  { word: "桜（さくら）", meaning: "Bunga sakura" },
	  { word: "（お）弁当（べんとう）", meaning: "Bekal makanan / Bento" },
	  { word: "朝（あさ）", meaning: "Pagi" },
	  { word: "夜（よる）", meaning: "Malam" },
	  { word: "毎日（まいにち）", meaning: "Setiap hari" },
	  { word: "毎朝（まいあさ）", meaning: "Setiap pagi" },
	  { word: "毎晩（まいばん）", meaning: "Setiap malam" },
	  { word: "朝ご飯（あさごはん）", meaning: "Sarapan" },
	  { word: "昼ご飯（ひるごはん）", meaning: "Makan siang" },
	  { word: "コンビニ", meaning: "Toko serba ada / minimarket" },
	  { word: "牛乳（ぎゅうにゅう）", meaning: "Susu" },
	  { word: "サラダ", meaning: "Salad" },
	  { word: "新聞（しんぶん）", meaning: "Koran" },
	  { word: "インターネット", meaning: "Internet" },
	  { word: "読みます（よみます）", meaning: "Membaca" },
	  { word: "勉強します（べんきょうします）", meaning: "Belajar" },
	  { word: "聞きます（ききます）", meaning: "Mendengarkan" },
	  { word: "CD（シーディー）", meaning: "CD" },
	  { word: "卵（たまご）", meaning: "Telur" },
	  { word: "食べます（たべます）", meaning: "Makan" },
	  { word: "行きます（いきます）", meaning: "Pergi ke" },
	  { word: "見ます（みます）", meaning: "Melihat" },
	  { word: "なに", meaning: "Apa" },
	  { word: "～や", meaning: "~ dan (digunakan dalam daftar benda)" },
	  { word: "何も（なにも）", meaning: "Tidak ada apa-apa" },
	  { word: "うち", meaning: "Rumah" },
	  { word: "果物（くだもの）", meaning: "Buah-buahan" },
	  { word: "チーズ", meaning: "Keju" },
	  { word: "買います（かいます）", meaning: "Membeli" },
	  { word: "会社（かいしゃ）", meaning: "Perusahaan / Kantor" },
	  { word: "学校（がっこう）", meaning: "Sekolah" },
	  { word: "寝ます（ねます）", meaning: "Tidur" },
	  { word: "起きます（おきます）", meaning: "Bangun (dari tidur)" },
	  { word: "来ます（きます）", meaning: "Datang" },
	  { word: "テレビ", meaning: "Televisi" },
	  { word: "DVD（ディーブイディー）", meaning: "DVD" },
	  { word: "働きます（はたらきます）", meaning: "Bekerja" },
	  { word: "どこへも", meaning: "Ke mana pun" }
		  ],
	"Lesson 4": [
	  { word: "北（きた）", meaning: "Utara" },
	  { word: "南（みなみ）", meaning: "Selatan" },
	  { word: "東（ひがし）", meaning: "Timur" },
	  { word: "西（にし）", meaning: "Barat" },
	  { word: "真ん中（まんなか）", meaning: "Tengah / Di tengah-tengah" },
	  { word: "どのくらい", meaning: "Seberapa lama / berapa lama" },
	  { word: "～時間（～じかん）", meaning: "～ jam (durasi waktu)" },
	  { word: "～分（～ふん／～ぷん）", meaning: "～ menit" },
	  { word: "くらい", meaning: "Sekitar / kira-kira" },
	  { word: "車（くるま）", meaning: "Mobil" },
	  { word: "新幹線（しんかんせん）", meaning: "Kereta cepat (Shinkansen)" },
	  { word: "電車（でんしゃ）", meaning: "Kereta listrik" },
	  { word: "飛行機（ひこうき）", meaning: "Pesawat terbang" },
	  { word: "自転車（じてんしゃ）", meaning: "Sepeda" },
	  { word: "バイク", meaning: "Sepeda motor / motor" },
	  { word: "駅（えき）", meaning: "Stasiun" },
	  { word: "町（まち）", meaning: "Kota / daerah" },
	  { word: "歩いて（あるいて）", meaning: "Berjalan kaki" },
	  { word: "～くらい", meaning: "Kira-kira / sekitar (jumlah)" },
	  { word: "お寺（おてら）", meaning: "Kuil Buddha" },
	  { word: "ビル", meaning: "Gedung (bangunan tinggi)" },
	  { word: "川（かわ）", meaning: "Sungai" },
	  { word: "人（ひと）", meaning: "Orang" },
	  { word: "緑（みどり）", meaning: "Hijau / tanaman hijau" },
	  { word: "新しい（あたらしい）", meaning: "Baru" },
	  { word: "古い（ふるい）", meaning: "Lama / tua (benda)" },
	  { word: "大きい（おおきい）", meaning: "Besar" },
	  { word: "小さい（ちいさい）", meaning: "Kecil" },
	  { word: "高い（たかい）", meaning: "Tinggi / mahal" },
	  { word: "低い（ひくい）", meaning: "Rendah" },
	  { word: "多い（おおい）", meaning: "Banyak" },
	  { word: "少ない（すくない）", meaning: "Sedikit" },
	  { word: "静か［な］（しずか［な］）", meaning: "Tenang" },
	  { word: "にぎやか［な］", meaning: "Ramai" },
	  { word: "きれい［な］", meaning: "Indah / bersih / cantik" },
	  { word: "山（やま）", meaning: "Gunung" },
	  { word: "教会（きょうかい）", meaning: "Gereja" },
	  { word: "お城（おしろ）", meaning: "Kastil / Istana" },
	  { word: "神社（じんじゃ）", meaning: "Kuil Shinto" },
	  { word: "いい", meaning: "Bagus / Baik" },
	  { word: "有名（ゆうめい）", meaning: "Terkenal" },
	  { word: "ところ", meaning: "Tempat" },
	  { word: "温泉（おんせん）", meaning: "Pemandian air panas" },
	  { word: "あります", meaning: "Ada (untuk benda mati)" },
	  { word: "そして", meaning: "Kemudian" },
	  { word: "暑い（あつい）", meaning: "Panas (cuaca)" },
	  { word: "寒い（さむい）", meaning: "Dingin (cuaca)" },
	  { word: "暖かい（あたたかい）", meaning: "Hangat" },
	  { word: "涼しい（すずしい）", meaning: "Sejuk" },
	  { word: "天気がいい（てんきがいい）", meaning: "Cuacanya bagus / cerah" },
	  { word: "天気が悪い（てんきがわるい）", meaning: "Cuacanya buruk / mendung dsb." },
	  { word: "一年中（いちねんじゅう）", meaning: "Sepanjang tahun" },
	  { word: "雪（ゆき）", meaning: "Salju" },
	  { word: "雨（あめ）", meaning: "Hujan" },
	  { word: "そうですね", meaning: "Ya, benar / Betul sekali" },
	  { word: "ペキン", meaning: "Beijing (Ibukota Tiongkok)" },
	  { word: "とても", meaning: "Sangat" },
	  { word: "少し（すこし）", meaning: "Sedikit" },
	  { word: "あまり", meaning: "Tidak begitu / Tidak terlalu" },
	  { word: "プサン", meaning: "Busan (nama kota di Korea Selatan)" },
	  { word: "どう", meaning: "Bagaimana" },
	  { word: "温かい（あたたかい）", meaning: "Hangat" },
	  { word: "熱い（あつい）", meaning: "Panas (untuk benda/minuman)" },
	  { word: "冷たい（つめたい）", meaning: "Dingin (untuk benda/minuman)" },
	  { word: "おいしい", meaning: "Enak / Lezat" },
	  { word: "甘い（あまい）", meaning: "Manis" },
	  { word: "辛い（からい）", meaning: "Pedas" },
	  { word: "苦い（にがい）", meaning: "Pahit" },
	  { word: "すっぱい", meaning: "Asam" },
	  { word: "日（ひ）", meaning: "Hari / Matahari" },
	  { word: "サムゲタン", meaning: "Samgyetang (sup ayam Korea)" },	
		  ],
		  "Lesson 5": [
	   { word: "昨日（きのう）", meaning: "Kemarin" },
	   { word: "家（いえ）", meaning: "Rumah" },
	   { word: "部屋（へや）", meaning: "Kamar" },
	   { word: "デパート", meaning: "Departemen store / Toserba" },
	   { word: "ゲーム", meaning: "Permainan / Game" },
	   { word: "友達（ともだち）", meaning: "Teman" },
	   { word: "会います（あいます）", meaning: "Bertemu (di negara <negara>)" },
	   { word: "買い物します（かいものします）", meaning: "Berbelanja" },
	   { word: "洗濯します（せんたくします）", meaning: "Mencuci (pakaian)" },
	   { word: "掃除します（そうじします）", meaning: "Membersihkan" },
	   { word: "週末（しゅうまつ）", meaning: "Akhir pekan / weekend" },
	   { word: "どこか", meaning: "Ke suatu tempat (entah ke mana)" },
	   { word: "作ります（つくります）", meaning: "Membuat (sesuatu)" },
	   { word: "食事します（しょくじします）", meaning: "Makan / melakukan makan" },
	   { word: "美術館（びじゅつかん）", meaning: "Museum seni" },
	   { word: "家族（かぞく）", meaning: "Keluarga" },
	   { word: "恋人（こいびと）", meaning: "Kekasih / pacar" },
	   { word: "ルームメイト", meaning: "Teman sekamar (roommate)" },
	   { word: "1人で（ひとりで）", meaning: "Sendirian" },
	   { word: "今日（きょう）", meaning: "Hari ini" },
	   { word: "明日（あした）", meaning: "Besok" },
	   { word: "あさって", meaning: "Lusa" },
	   { word: "先週（せんしゅう）", meaning: "Minggu lalu" },
	   { word: "おととい", meaning: "Kemarin lusa" },
	   { word: "それから", meaning: "Setelah itu / lalu / kemudian" },
	   { word: "高い（たかい）", meaning: "Mahal / tinggi" },
	   { word: "安い（やすい）", meaning: "Murah" },
	   { word: "気持ちがいい（きもちがいい）", meaning: "Enak rasanya / nyaman" },
	   { word: "楽しい（たのしい）", meaning: "Menyenangkan / seru" },
	   { word: "ひま（な）", meaning: "Senggang / waktu luang" },
	   { word: "忙しい（いそがしい）", meaning: "Sibuk" },
	   { word: "難しい（むずかしい）", meaning: "Sulit / susah" },
	   { word: "大変（たいへん）", meaning: "Berat / sulit / parah" },
	   { word: "簡単（かんたん）", meaning: "Mudah / gampang" },
	   { word: "今朝（けさ）", meaning: "Pagi ini" },
	   { word: "先月（せんげつ）", meaning: "Bulan lalu" },
	   { word: "去年（きょねん）", meaning: "Tahun lalu" },
	   { word: "難しい（むずかしい）", meaning: "Sulit" },
	   { word: "天気（てんき）", meaning: "Cuaca" },
	   { word: "服（ふく）", meaning: "Baju / Pakaian" },
	   { word: "登ります（のぼります）", meaning: "Mendaki (ke tempat tinggi)" },
	   { word: "入ります（はいります）", meaning: "Masuk (ke dalam)" },
	   { word: "晩ご飯（ばんごはん）", meaning: "Makan malam" },
	   { word: "風邪（かぜ）", meaning: "Masuk angin / Flu" },
	   { word: "どうして", meaning: "Kenapa / Mengapa" },
	   { word: "～から", meaning: "Karena ~" },
	   { word: "今度（こんど）", meaning: "Lain kali / Waktu berikutnya" },
	   { word: "自転車（じてんしゃ）", meaning: "Sepeda" },
	   { word: "ほしい", meaning: "Ingin (kata sifat, untuk benda)" },
	   { word: "好き（すき）", meaning: "Suka" },
	   { word: "嫌い（きらい）", meaning: "Tidak suka / Benci" },
	   { word: "アニメ", meaning: "Anime" },
	   { word: "景色（けしき）", meaning: "Pemandangan" },
	   { word: "写真（しゃしん）", meaning: "Foto" },
	   { word: "撮ります（とります）", meaning: "Mengambil (foto)" },
	   { word: "今晩（こんばん）", meaning: "Malam ini" },
	   { word: "今年（ことし）", meaning: "Tahun ini" },
	   { word: "来年（らいねん）", meaning: "Tahun depan" },
	   { word: "絵（え）", meaning: "Gambar / Lukisan" },
	   { word: "借ります（かります）", meaning: "Meminjam" },
	   { word: "新宿（しんじゅく）", meaning: "Shinjuku (nama tempat di Tokyo)" }
		  ],
		  
		  "Lesson 6": [
		  { word: "名前（なまえ）", meaning: "Nama" },
		  { word: "会います（あいます）", meaning: "Bertemu" },
		  { word: "駅（えき）", meaning: "Stasiun" },
		  { word: "どこ", meaning: "Di mana" },
		  { word: "何時（なんじ）", meaning: "Jam berapa" },
		  { word: "どうですか", meaning: "Bagaimana" },
		  { word: "18時（じ）ごろ", meaning: "Sekitar jam 18:00" },
		  { word: "映画館（えいがかん）", meaning: "Bioskop" },
		  { word: "そうしましょう", meaning: "Mari kita lakukan itu" },
		  { word: "わかりました", meaning: "Saya mengerti" },
		  { word: "ステーキ", meaning: "Steak" },
		  { word: "すきやき", meaning: "Sukiyaki" },
		  { word: "まだ", meaning: "Belum" },
		  { word: "もう", meaning: "Sudah" },
		  { word: "遊びます（あそびます）", meaning: "Bermain" },
		  { word: "お好み焼き（おこのみやき）", meaning: "Okonomiyaki" },
		  { word: "コース", meaning: "Jalur / Paket" },
		  { word: "東京タワー（とうきょうタワー）", meaning: "Tokyo Tower" },
		  { word: "スカイツリー", meaning: "Tokyo Skytree" },
		  { word: "地下鉄（ちかてつ）", meaning: "Kereta bawah tanah" },
		  { word: "食べ放題（たべほうだい）", meaning: "Makan sepuasnya" },
		  { word: "どちら", meaning: "Yang mana?" },
		  { word: "どちらも", meaning: "Dua-duanya" },
		  { word: "ツアー", meaning: "Tur" },
		  { word: "近い（ちかい）", meaning: "Dekat" },
		  { word: "遠い（とおい）", meaning: "Jauh" },
		  { word: "早い（はやい）", meaning: "Cepat / Awal" },
		  { word: "広い（ひろい）", meaning: "Luas" },
		  { word: "食べ物（たべもの）", meaning: "Makanan" },
		  { word: "飲み物（のみもの）", meaning: "Minuman" },
		  { word: "居酒屋（いざかや）", meaning: "Bar (minum tradisional Jepang)" },
		  { word: "全部（ぜんぶ）", meaning: "Semua" },
		  { word: "ジャズ", meaning: "Jazz" },
		  { word: "歌手（かしゅ）", meaning: "Penyanyi" },
		  { word: "季節（きせつ）", meaning: "Musim" },
		  { word: "コメディー", meaning: "Komedi" },
		  { word: "いちばん", meaning: "Paling / Nomor satu" },
		  { word: "チケット", meaning: "Tiket" },
		  { word: "～枚（～まい）", meaning: "Lembar (satuan)" },
		  { word: "地図（ちず）", meaning: "Peta" },
		  { word: "水着（みずぎ）", meaning: "Pakaian renang" },
		  { word: "今週（こんしゅう）", meaning: "Minggu ini" },
		  { word: "来週（らいしゅう）", meaning: "Minggu depan" },
		  { word: "今月（こんげつ）", meaning: "Bulan ini" },
		  { word: "来月（らいげつ）", meaning: "Bulan depan" },
		  { word: "今晩（こんばん）", meaning: "Malam ini" },
		  { word: "あります", meaning: "Ada (untuk benda)" },
		  { word: "祭（まつり）", meaning: "Festival" },
		  { word: "試合（しあい）", meaning: "Pertandingan" },
		  { word: "野球（やきゅう）", meaning: "Baseball" },
		  { word: "セール", meaning: "Diskon / Obral" },
		  { word: "カラオケ", meaning: "Karaoke" },
		  { word: "コンサート", meaning: "Konser" },
		  { word: "一緒に（いっしょに）", meaning: "Bersama-sama" },
		  { word: "いいですね", meaning: "Bagus ya / Kedengarannya bagus" },
		  { word: "ああ", meaning: "Ah / Iya" },
		  { word: "すみません", meaning: "Permisi / Maaf" },
		  { word: "またこんど", meaning: "Lain kali" },
		  { word: "ちょっと（断るときの言い方）", meaning: "Maaf, agak sulit... (menolak)" },
		  { word: "約束（やくそく）", meaning: "Janji" },
		  { word: "用事（ようじ）", meaning: "Urusan" },
		  { word: "残念（ざんねん）", meaning: "Sayang sekali / Menyesal" }
		  ],
	    
		"Lesson 7": [
	   { "word": "ピザ", "meaning": "Pizza" },
	  { "word": "まだ", "meaning": "Masih" },
	  { "word": "もう", "meaning": "Sudah" },
	  { "word": "たくさん", "meaning": "Banyak" },
	  { "word": "少し（すこし）", "meaning": "Sedikit" },
	  { "word": "窓（まど）", "meaning": "Jendela" },
	  { "word": "開けます（あけます）", "meaning": "Membuka" },
	  { "word": "閉めます（しめます）", "meaning": "Menutup" },
	  { "word": "持ちます（もちます）", "meaning": "Membawa" },
	  { "word": "持ってきます（もってきます）", "meaning": "Membawa ke sini" },
	  { "word": "吸います（すいます）", "meaning": "Menghirup / Merokok" },
	  { "word": "歌います（うたいます）", "meaning": "Menyanyi" },
	  { "word": "弾きます（ひきます）", "meaning": "Memainkan (alat musik)" },
	  { "word": "かけます", "meaning": "Menelepon" },
	  { "word": "話します（はなします）", "meaning": "Berbicara" },
	  { "word": "台所（だいどころ）", "meaning": "Dapur" },
	  { "word": "電話（でんわ）", "meaning": "Telepon" },
	  { "word": "たばこ", "meaning": "Rokok" },
	  { "word": "歌（うた）", "meaning": "Lagu" },
	  { "word": "ギター", "meaning": "Gitar" },
	  { "word": "ソファー", "meaning": "Sofa" },
	  { "word": "どの", "meaning": "Yang mana (sebelum kata benda)" },
	  { "word": "どれ", "meaning": "Yang mana (sendiri)" },
	  { "word": "この", "meaning": "Ini (sebelum kata benda)" },
	  { "word": "その", "meaning": "Itu (sebelum kata benda)" },
	  { "word": "あの", "meaning": "Itu di sana (sebelum kata benda)" },
	  { "word": "これ", "meaning": "Ini" },
	  { "word": "それ", "meaning": "Itu" },
	  { "word": "あれ", "meaning": "Itu di sana" },
	  { "word": "携帯電話（けいたいでんわ）", "meaning": "Telepon genggam" },
	  { "word": "醤油（しょうゆ）", "meaning": "Kecap asin" },
	  { "word": "佐藤（さとう）", "meaning": "Gula" },
	  { "word": "ボトル", "meaning": "Botol" },
	  { "word": "お茶（おちゃ）", "meaning": "Teh" },
	  { "word": "電子レンジ（でんしレンジ）", "meaning": "Microwave" },
	  { "word": "漢字（かんじ）", "meaning": "Kanji" },
	  { "word": "聞きます（ききます）", "meaning": "Mendengar / Bertanya" },
	  { "word": "教えます（おしえます）", "meaning": "Mengajarkan / Memberi tahu" },
	  { "word": "すみませんが", "meaning": "Permisi, maaf…" },
	  { "word": "スプーン", "meaning": "Sendok" },
	  { "word": "ナイフ", "meaning": "Pisau" },
	  { "word": "フォーク", "meaning": "Garpu" },
	  { "word": "はし", "meaning": "Sumpit" },
	  { "word": "切ります（きります）", "meaning": "Memotong" },
	  { "word": "紙（かみ）", "meaning": "Kertas" },
	  { "word": "はさみ", "meaning": "Gunting" },
	  { "word": "手（て）", "meaning": "Tangan" },
	  { "word": "塩（しお）", "meaning": "Garam" },
	  { "word": "お皿（おさら）", "meaning": "Piring" },
	  { "word": "冷蔵庫（れいぞうこ）", "meaning": "Kulkas" },
	  { "word": "コップ", "meaning": "Gelas" },
	  { "word": "いす", "meaning": "Kursi" },
	  { "word": "手伝います（てつだいます）", "meaning": "Membantu" },
	  { "word": "洗います（あらいます）", "meaning": "Mencuci" },
	  { "word": "書きます（かきます）", "meaning": "Menulis" },
	  { "word": "入れます（いれます）", "meaning": "Memasukkan" },
	  { "word": "出します（だします）", "meaning": "Mengeluarkan" },
	  { "word": "貸します（かします）", "meaning": "Meminjamkan" },
	  { "word": "取ります（とります）", "meaning": "Mengambil" },
	  { "word": "置きます（おきます）", "meaning": "Meletakkan" },
	  { "word": "使います（つかいます）", "meaning": "Menggunakan" },
	  { "word": "持って行きます（もっていきます）", "meaning": "Membawa pergi" },
	  { "word": "死にます（しにます）", "meaning": "Mati" },
	  { "word": "間（あいだ）", "meaning": "Antara" },
	  { "word": "近く（ちかく）", "meaning": "Dekat" },
	  { "word": "木（き）", "meaning": "Pohon" },
	  { "word": "あります", "meaning": "Ada (untuk benda)" },
	  { "word": "テーブル", "meaning": "Meja" },
	  { "word": "花屋（はなや）", "meaning": "Toko bunga" },
	  { "word": "スーパー", "meaning": "Supermarket" },
	  { "word": "図書館（としょかん）", "meaning": "Perpustakaan" },
	  { "word": "郵便局（ゆうびんきょく）", "meaning": "Kantor pos" },
	  { "word": "交番（こうばん）", "meaning": "Pos polisi" },
	  { "word": "バス停（バスてい）", "meaning": "Halte bus" },
	  { "word": "隣（となり）", "meaning": "Sebelah" },
	  { "word": "中（なか）", "meaning": "Dalam" },
	  { "word": "外（そと）", "meaning": "Luar" },
	  { "word": "前（まえ）", "meaning": "Depan" },
	  { "word": "後ろ（うしろ）", "meaning": "Belakang" },
	  { "word": "横（よこ）", "meaning": "Samping" },
	  { "word": "上（うえ）", "meaning": "Atas" },
	  { "word": "下（した）", "meaning": "Bawah" }
		  ],
		  
		  "Lesson 8": [
	     { "word": "～人（にん）", "meaning": "Orang (satuan)" },
  { "word": "住みます（すみます）", "meaning": "Tinggal" },
  { "word": "娘（むすめ）", "meaning": "Anak perempuan" },
  { "word": "息子（むすこ）", "meaning": "Anak laki-laki" },
  { "word": "子ども（こども）", "meaning": "Anak (sendiri)" },
  { "word": "妻（つま）", "meaning": "Istri (sendiri)" },
  { "word": "夫（おっと）", "meaning": "Suami (sendiri)" },
  { "word": "妹（いもうと）", "meaning": "Adik perempuan (sendiri)" },
  { "word": "弟（おとうと）", "meaning": "Adik laki-laki (sendiri)" },
  { "word": "姉（あね）", "meaning": "Kakak perempuan (sendiri)" },
  { "word": "兄（あに）", "meaning": "Kakak laki-laki (sendiri)" },
  { "word": "兄弟（きょうだい）", "meaning": "Saudara kandung" },
  { "word": "母（はは）", "meaning": "Ibu (sendiri)" },
  { "word": "父（ちち）", "meaning": "Ayah (sendiri)" },
  { "word": "両親（りょうしん）", "meaning": "Orang tua" },
  { "word": "じゅっぴき", "meaning": "Sepuluh ekor" },
  { "word": "きゅうひき", "meaning": "Sembilan ekor" },
  { "word": "はっぴき", "meaning": "Delapan ekor" },
  { "word": "ななひき", "meaning": "Tujuh ekor" },
  { "word": "ろっぴき", "meaning": "Enam ekor" },
  { "word": "ごひき", "meaning": "Lima ekor" },
  { "word": "よんひき", "meaning": "Empat ekor" },
  { "word": "さんびき", "meaning": "Tiga ekor" },
  { "word": "にひき", "meaning": "Dua ekor" },
  { "word": "いっぴき", "meaning": "Seekor" },
  { "word": "匹（～ひき）", "meaning": "Ekor (satuan hewan)" },
  { "word": "猫（ねこ）", "meaning": "Kucing" },
  { "word": "ペット", "meaning": "Hewan peliharaan" },
  { "word": "お子さん（おこさん）", "meaning": "Anak (orang lain)" },
  { "word": "います", "meaning": "Ada (makhluk hidup)" },
  { "word": "ピアノ", "meaning": "Piano" },
  { "word": "大学生（だいがくせい）", "meaning": "Mahasiswa" },
  { "word": "高校生（こうこうせい）", "meaning": "Siswa SMA" },
  { "word": "看護師（かんごし）", "meaning": "Perawat" },
  { "word": "医者（いしゃ）", "meaning": "Dokter" },
  { "word": "妹さん（いもうとさん）", "meaning": "Adik perempuan (orang lain)" },
  { "word": "弟さん（おとうとさん）", "meaning": "Adik laki-laki (orang lain)" },
  { "word": "お姉さん（おねえさん）", "meaning": "Kakak perempuan (orang lain)" },
  { "word": "お兄さん（おにいさん）", "meaning": "Kakak laki-laki (orang lain)" },
  { "word": "お母さん（おかあさん）", "meaning": "Ibu (orang lain)" },
  { "word": "お父さん（おとうさん）", "meaning": "Ayah (orang lain)" },
  { "word": "奥さん（おくさん）", "meaning": "Istri (orang lain)" },
  { "word": "ご主人（ごしゅじん）", "meaning": "Suami (orang lain)" },
  { "word": "かわいい", "meaning": "Lucu / imut" },
  { "word": "かっこいい", "meaning": "Keren" },
  { "word": "背が低い（せがひくい）", "meaning": "Bertubuh pendek" },
  { "word": "背が高い（せがたかい）", "meaning": "Bertubuh tinggi" },
  { "word": "短い（みじかい）", "meaning": "Pendek" },
  { "word": "長い（ながい）", "meaning": "Panjang" },
  { "word": "耳（みみ）", "meaning": "Telinga" },
  { "word": "口（くち）", "meaning": "Mulut" },
  { "word": "顔（かお）", "meaning": "Wajah" },
  { "word": "鼻（はな）", "meaning": "Hidung" },
  { "word": "目（め）", "meaning": "Mata" },
  { "word": "体（からだ）", "meaning": "Tubuh" },
  { "word": "足（あし）", "meaning": "Kaki" },
  { "word": "髪（かみ）", "meaning": "Rambut" },
  { "word": "うさぎ", "meaning": "Kelinci" },
  { "word": "茶色い（ちゃいろい）", "meaning": "Cokelat" },
  { "word": "白い（しろい）", "meaning": "Putih" },
  { "word": "黒い（くろい）", "meaning": "Hitam" },
  { "word": "まじめな", "meaning": "Serius / rajin" },
  { "word": "親切な（しんせつな）", "meaning": "Baik hati / ramah" },
  { "word": "元気な（げんきな）", "meaning": "Sehat / semangat" },
  { "word": "頭がいい（あたまがいい）", "meaning": "Pintar" },
  { "word": "優しい（やさしい）", "meaning": "Baik hati / ramah" },
  { "word": "結婚式（けっこんしき）", "meaning": "Upacara pernikahan" },
  { "word": "電話（でんわ）をします", "meaning": "Menelepon" },
  { "word": "送ります（おくります）", "meaning": "Mengirim" },
  { "word": "メール", "meaning": "Email" },
  { "word": "もうすぐ", "meaning": "Sebentar lagi / segera" },
  { "word": "あげます", "meaning": "Memberi (kepada orang lain)" },
  { "word": "プレゼント", "meaning": "Hadiah" },
  { "word": "手紙（てがみ）", "meaning": "Surat" },
  { "word": "カード", "meaning": "Kartu" },
  { "word": "辞書（じしょ）", "meaning": "Kamus" },
  { "word": "ネックレス", "meaning": "Kalung" },
  { "word": "かさ", "meaning": "Payung" },
  { "word": "ノート", "meaning": "Buku catatan / Notebook" },
  { "word": "チョコレート", "meaning": "Cokelat" },
  { "word": "もらいます", "meaning": "Menerima" },
  { "word": "靴下（くつした）", "meaning": "Kaos kaki" },
  { "word": "（お）金（かね）", "meaning": "Uang" },
  { "word": "クリスマス", "meaning": "Natal" },
  { "word": "バレンタインデー", "meaning": "Hari Valentine" },
  { "word": "くれます", "meaning": "Memberi (kepada saya)" }
		  ],
		  
		
		  "Lesson 9": [
	   { "word": "特に（とくに）", "meaning": "Terutama" },
  { "word": "クラシック", "meaning": "Klasik" },
  { "word": "小説（しょうせつ）", "meaning": "Novel" },
  { "word": "ポップス", "meaning": "Pop" },
  { "word": "できます", "meaning": "Bisa" },
  { "word": "イベント", "meaning": "Acara" },
  { "word": "ダイビング", "meaning": "Menyelam" },
  { "word": "ダンス", "meaning": "Tari" },
  { "word": "～クラブ", "meaning": "Klub〜" },
  { "word": "入ります（はいります）", "meaning": "Masuk ke〜" },
  { "word": "参加します（さんか）", "meaning": "Ikut serta dalam〜" },
  { "word": "すごい", "meaning": "Hebat" },
  { "word": "いろいろ（な）", "meaning": "Berbagai macam" },
  { "word": "掲示板（けいじばん）", "meaning": "Papan pengumuman" },
  { "word": "書道（しょどう）", "meaning": "Kaligrafi Jepang" },
  { "word": "～教室（～きょうしつ）", "meaning": "Kelas〜" },
  { "word": "習います（ならいます）", "meaning": "Belajar〜" },
  { "word": "乗ります（のります）", "meaning": "Naik〜" },
  { "word": "申し込みます（もうしこみます）", "meaning": "Mendaftar" },
  { "word": "上手に（じょうずに）", "meaning": "Dengan baik / mahir" },
  { "word": "歌います（うたいます）", "meaning": "Menyanyi" },
  { "word": "絵をかきます（えをかきます）", "meaning": "Melukis / Menggambar" },
  { "word": "教えます（おしえます）", "meaning": "Mengajar" },
  { "word": "ギターをひきます（弾きます）", "meaning": "Bermain gitar" },
  { "word": "作ります（つくります）", "meaning": "Membuat" },
  { "word": "話します（はなします）", "meaning": "Berbicara" },
  { "word": "泳ぎます（およぎます）", "meaning": "Berenang" },
  { "word": "コンピューター", "meaning": "Komputer" },
  { "word": "英語（えいご）", "meaning": "Bahasa Inggris" },
  { "word": "自転車（じてんしゃ）", "meaning": "Sepeda" },
  { "word": "辛い（からい）", "meaning": "Pedas" },
  { "word": "日本料理（にほんりょうり）", "meaning": "Masakan Jepang" },
  { "word": "受付（うけつけ）", "meaning": "Resepsionis" },
  { "word": "カード", "meaning": "Kartu" },
  { "word": "外国人登録証（がいこくじんとうろくしょう）", "meaning": "Kartu identitas orang asing" },
  { "word": "住所（じゅうしょ）", "meaning": "Alamat" },
  { "word": "電話番号（でんわばんごう）", "meaning": "Nomor telepon" },
  { "word": "～番（～ばん）", "meaning": "Nomor〜" },
  { "word": "どうやって", "meaning": "Bagaimana caranya" },
  { "word": "言います（いいます）", "meaning": "Mengatakan" },
  { "word": "払います（はらいます）", "meaning": "Membayar" },
  { "word": "降ります（おります）", "meaning": "Turun dari〜" },
  { "word": "見せます（みせます）", "meaning": "Memperlihatkan" },
  { "word": "予約します（よやくします）", "meaning": "Memesan / Reservasi" },
  { "word": "地域（ちいき）", "meaning": "Wilayah / Daerah" },
  { "word": "交流会（こうりゅうかい）", "meaning": "Pertemuan pertukaran budaya" },
  { "word": "釣り（つり）", "meaning": "Memancing" },
  { "word": "漫画（まんが）", "meaning": "Komik / Manga" },
  { "word": "切手（きって）", "meaning": "Perangko" },
  { "word": "お菓子（おかし）", "meaning": "Permen / Makanan ringan" },
  { "word": "運転します（うんてんします）", "meaning": "Menyetir" },
  { "word": "集めます（あつめます）", "meaning": "Mengumpulkan" },
  { "word": "泳ぎます（およぎます）", "meaning": "Berenang" },
  { "word": "書きます（かきます）", "meaning": "Menulis" },
  { "word": "いつも", "meaning": "Selalu" },
  { "word": "よく", "meaning": "Sering" },
  { "word": "時々（ときどき）", "meaning": "Kadang-kadang" },
  { "word": "あまり", "meaning": "Jarang / Tidak terlalu" },
  { "word": "全然（ぜんぜん）", "meaning": "Sama sekali tidak" },
  { "word": "最近（さいきん）", "meaning": "Akhir-akhir ini" },
  { "word": "でも", "meaning": "Tapi / Namun" },
  { "word": "ドラマ", "meaning": "Drama" },
  { "word": "プール", "meaning": "Kolam renang" },
  { "word": "～日（にち）", "meaning": "Hari〜" },
  { "word": "～週間（しゅうかん）", "meaning": "Minggu〜" },
  { "word": "～月（げつ）", "meaning": "Bulan〜" },
  { "word": "～年（ねん）", "meaning": "Tahun〜" },
  { "word": "～回（かい）", "meaning": "Kali〜" },
  { "word": "～冊（さつ）", "meaning": "Jumlah buku〜" },
  { "word": "～本（ほん、ぽん、ぼん）", "meaning": "Batang〜 (untuk benda panjang)" },
  { "word": "～杯（はい、ぱい、ばい）", "meaning": "Gelas / Cangkir〜" }
		  ],
		  
		  "Lesson 10": [
	   { "word": "集合（しゅうごう）", "meaning": "Berkumpul" },
  { "word": "リーダー", "meaning": "Pemimpin" },
  { "word": "点呼（てんこ）", "meaning": "Apel / Absensi" },
  { "word": "探す（さがす）", "meaning": "Mencari" },
  { "word": "薬（くすり）", "meaning": "Obat" },
  { "word": "飲みます（のみます）", "meaning": "Minum [obat]" },
  { "word": "よくわかりません", "meaning": "Saya tidak begitu paham" },
  { "word": "橋（はし）", "meaning": "Jembatan" },
  { "word": "声（こえ）", "meaning": "Suara (manusia)" },
  { "word": "音（おと）", "meaning": "Suara (benda)" },
  { "word": "見えます（みえます）", "meaning": "Terlihat" },
  { "word": "聞こえます（きこえます）", "meaning": "Terdengar" },
  { "word": "渡ります（わたります）", "meaning": "Menyeberang" },
  { "word": "曲がります（まがります）", "meaning": "Belok" },
  { "word": "右（みぎ）", "meaning": "Kanan" },
  { "word": "左（ひだり）", "meaning": "Kiri" },
  { "word": "交差点（こうさてん）", "meaning": "Perempatan" },
  { "word": "信号（しんごう）", "meaning": "Lampu lalu lintas" },
  { "word": "角（かど）", "meaning": "Sudut / Tikungan" },
  { "word": "道（みち）", "meaning": "Jalan" },
  { "word": "まっすぐ", "meaning": "Lurus" },
  { "word": "～つ目（～め）", "meaning": "Yang ke- (urutan)" },
  { "word": "カーテン", "meaning": "Gorden" },
  { "word": "荷物（にもつ）", "meaning": "Barang bawaan" },
  { "word": "パンフレット", "meaning": "Pamflet" },
  { "word": "お土産（みやげ）", "meaning": "Oleh-oleh" },
  { "word": "座ります（すわります）", "meaning": "Duduk di" },
  { "word": "入ります（はいります）", "meaning": "Masuk ke" },
  { "word": "他（ほか）", "meaning": "Yang lain" },
  { "word": "皆さん（みなさん）", "meaning": "Semuanya" },
  { "word": "お客さん（おきゃくさん）", "meaning": "Tamu / Pelanggan" },
  { "word": "大切（たいせつ）", "meaning": "Penting" },
  { "word": "迷惑（めいわく）", "meaning": "Gangguan / Merepotkan" },
  { "word": "押します（おします）", "meaning": "Mendorong" },
  { "word": "立ちます（たちます）", "meaning": "Berdiri" },
  { "word": "なくします", "meaning": "Kehilangan" },
  { "word": "遅れます（おくれます）", "meaning": "Terlambat" },
  { "word": "集合します（しゅうごうします）", "meaning": "Berkumpul (bentuk sopan)" },
  { "word": "持って帰ります（もってかえります）", "meaning": "Membawa pulang" },
  { "word": "動物園（どうぶつえん）", "meaning": "Kebun binatang" },
  { "word": "サル", "meaning": "Monyet" },
  { "word": "コアラ", "meaning": "Koala" },
  { "word": "ゾウ", "meaning": "Gajah" },
  { "word": "ペンギン", "meaning": "Penguin" },
  { "word": "鳥（とり）", "meaning": "Burung" },
  { "word": "クマ", "meaning": "Beruang" },
  { "word": "えさ", "meaning": "Makanan hewan" },
  { "word": "登ります（のぼります）", "meaning": "Memanjat / Mendaki" },
  { "word": "飛びます（とびます）", "meaning": "Terbang" },
  { "word": "歩きます（あるきます）", "meaning": "Berjalan kaki" },
  { "word": "～たち", "meaning": "Penanda jamak (misalnya: わたしたち = kami)" },
  { "word": "バナナ", "meaning": "Pisang" },
  { "word": "観覧車（かんらんしゃ）", "meaning": "Bianglala" },
  { "word": "ボール", "meaning": "Bola" },
  { "word": "入口（いりぐち）", "meaning": "Pintu masuk" },
  { "word": "出口（でぐち）", "meaning": "Pintu keluar" },
  { "word": "おなか", "meaning": "Perut" },
  { "word": "休みます（やすみます）", "meaning": "Istirahat" },
  { "word": "お腹がすきます（おなかがすきます）", "meaning": "Lapar" },
  { "word": "喉が渇きます（のどがかわきます）", "meaning": "Haus" },
  { "word": "疲れます（つかれます）", "meaning": "Lelah" },
  { "word": "やります", "meaning": "Melakukan (bentuk informal)" },
  { "word": "痛い（いたい）", "meaning": "Sakit (rasa sakit)" },
  { "word": "暗い（くらい）", "meaning": "Gelap" },
  { "word": "そろそろ", "meaning": "Sebentar lagi" },
  { "word": "なります", "meaning": "Menjadi" }
		  ],
		  
		  "Lesson 11": [
	   { "word": "会話（かいわ）", "meaning": "Percakapan" },
  { "word": "作文（さくぶん）", "meaning": "Karangan" },
  { "word": "はじめ", "meaning": "Permulaan" },
  { "word": "生活（せいかつ）", "meaning": "Kehidupan" },
  { "word": "一人暮らし（ひとりぐらし）", "meaning": "Tinggal sendiri" },
  { "word": "平日（へいじつ）", "meaning": "Hari kerja" },
  { "word": "寂しい（さびしい）", "meaning": "Kesepian" },
  { "word": "クラスメイト", "meaning": "Teman sekelas" },
  { "word": "慣れます（なれます）", "meaning": "Terbiasa" },
  { "word": "ひらがな", "meaning": "Hiragana" },
  { "word": "交流会（こうりゅうかい）", "meaning": "Acara pertukaran" },
  { "word": "ジョギング", "meaning": "Joging" },
  { "word": "日記（にっき）", "meaning": "Buku harian" },
  { "word": "たいてい", "meaning": "Biasanya" },
  { "word": "終わります（おわります）", "meaning": "Selesai" },
  { "word": "通います（かよいます）", "meaning": "Pergi (rutin)" },
  { "word": "散歩します（さんぽします）", "meaning": "Jalan-jalan" },
  { "word": "店長（てんちょう）", "meaning": "Manajer toko" },
  { "word": "頭（あたま）", "meaning": "Kepala" },
  { "word": "風をひきます（かぜをひきます）", "meaning": "Masuk angin" },
  { "word": "学校を休みます（がっこうをやすみます）", "meaning": "Tidak masuk sekolah" },
  { "word": "忘れます（わすれます）", "meaning": "Lupa" },
  { "word": "なかなか", "meaning": "Tidak mudah / cukup sulit (bentuk negatif)" },
  { "word": "祖父（そふ）", "meaning": "Kakek" },
  { "word": "卒業します（そつぎょうします）", "meaning": "Lulus" },
  { "word": "入学します（にゅうがくします）", "meaning": "Masuk sekolah/perguruan tinggi" },
  { "word": "別れます（わかれます）", "meaning": "Berpisah" },
  { "word": "小学生（しょうがくせい）", "meaning": "Murid SD" },
  { "word": "中学生（ちゅうがくせい）", "meaning": "Murid SMP" },
  { "word": "外国（がいこく）", "meaning": "Luar negeri" },
  { "word": "オリンピック", "meaning": "Olimpiade" },
  { "word": "選手（せんしゅ）", "meaning": "Atlet" },
  { "word": "始めます（はじめます）", "meaning": "Memulai" },
  { "word": "初めて（はじめて）", "meaning": "Pertama kali" },
  { "word": "それで", "meaning": "Lalu / kemudian" },
  { "word": "うん", "meaning": "Ya (informal)" },
  { "word": "ううん", "meaning": "Tidak (informal)" },
  { "word": "エアコン", "meaning": "AC (air conditioner)" },
  { "word": "消します（けします）", "meaning": "Mematikan (alat listrik)" },
  { "word": "つけます", "meaning": "Menyalakan" },
  { "word": "あめ", "meaning": "Hujan / Permen (tergantung konteks)" },
  { "word": "ごめん", "meaning": "Maaf (informal)" },
  { "word": "そっか", "meaning": "Oh begitu ya (informal)" },
  { "word": "また", "meaning": "Lagi / sampai jumpa" },
  { "word": "引っ越しします（ひっこしします）", "meaning": "Pindah rumah" }
		  ],
		  
		  "Lesson 12": [
	  { "word": "体調（たいちょう）", "meaning": "Kondisi tubuh" },
  { "word": "悪い（わるい）", "meaning": "Buruk / Jelek" },
  { "word": "症状（しょうじょう）", "meaning": "Gejala" },
  { "word": "早退（そうたい）", "meaning": "Pulang lebih awal" },
  { "word": "欠席（けっせき）", "meaning": "Tidak hadir" },
  { "word": "のど", "meaning": "Tenggorokan" },
  { "word": "調子（ちょうし）", "meaning": "Kondisi (fisik)" },
  { "word": "早く（はやく）", "meaning": "Cepat / Lebih cepat" },
  { "word": "食欲（しょくよく）", "meaning": "Nafsu makan" },
  { "word": "気持ちが悪い（きもちがわるい）", "meaning": "Merasa tidak enak / mual" },
  { "word": "熱（ねつ）", "meaning": "Demam / Panas badan" },
  { "word": "歯（は）", "meaning": "Gigi" },
  { "word": "けが", "meaning": "Luka" },
  { "word": "病気（びょうき）", "meaning": "Penyakit / Sakit" },
  { "word": "～度（ど）", "meaning": "Derajat (misal suhu)" },
  { "word": "お大事に（おだいじに）", "meaning": "Semoga lekas sembuh" },
  { "word": "それはいけませんね", "meaning": "Itu tidak baik ya" },
  { "word": "大丈夫（だいじょうぶ）", "meaning": "Tidak apa-apa / Baik saja" },
  { "word": "おかげさまで", "meaning": "Terima kasih atas perhatian Anda" },
  { "word": "飲み会（のみかい）", "meaning": "Acara minum bersama" },
  { "word": "治ります（なおります）", "meaning": "Sembuh" },
  { "word": "シャワー", "meaning": "Shower / Mandi pancuran" },
  { "word": "歯医者（はいしゃ）", "meaning": "Dokter gigi" },
  { "word": "やけど", "meaning": "Luka bakar" },
  { "word": "固い（かたい）", "meaning": "Keras" },
  { "word": "柔らかい（やわらかい）", "meaning": "Lunak / Lembut" },
  { "word": "＜を＞塗ります（ぬります）", "meaning": "Mengoleskan (salep)" },
  { "word": "＜を＞浴びます（あびます）", "meaning": "Mandi / Disiram" },
  { "word": "声を出します（こえをだします）", "meaning": "Mengeluarkan suara" },
  { "word": "もの", "meaning": "Benda" },
  { "word": "こと", "meaning": "Hal / Perkara" },
  { "word": "ゆっくり", "meaning": "Pelan-pelan" },
  { "word": "ゆっくりやすんでください", "meaning": "Silakan istirahat perlahan" },
  { "word": "できるだけ", "meaning": "Sebisa mungkin" },
  { "word": "睡眠（すいみん）", "meaning": "Tidur" },
  { "word": "以上（いじょう）", "meaning": "Sekian / Lebih dari" },
  { "word": "運動します（うんどうします）", "meaning": "Berolahraga" },
  { "word": "自分で（じぶんで）", "meaning": "Sendiri" },
  { "word": "お風呂（おふろ）", "meaning": "Bak mandi / Mandi" },
  { "word": "保険証（ほけんしょう）", "meaning": "Kartu asuransi" },
  { "word": "説明書（せつめいしょ）", "meaning": "Buku petunjuk" },
  { "word": "コンタクトレンズ", "meaning": "Lensa kontak" },
  { "word": "待合室（まちあいしつ）", "meaning": "Ruang tunggu" },
  { "word": "かゆい", "meaning": "Gatal" },
  { "word": "上着（うわぎ）", "meaning": "Jaket / Pakaian luar" },
  { "word": "＜を＞磨きます（みがきます）", "meaning": "Menggosok (gigi)" },
  { "word": "＜を＞出します（だします）", "meaning": "Mengeluarkan" },
  { "word": "＜を＞待ちます（まちます）", "meaning": "Menunggu" },
  { "word": "＜を＞準備します（じゅんびします）", "meaning": "Mempersiapkan" },
  { "word": "＜を＞脱ぎます（ぬぎます）", "meaning": "Melepas (pakaian)" },
  { "word": "横（よこ）になります", "meaning": "Berbaring menyamping" }
		  ],
		  
		   "Lesson 13": [
	  { "word": "相撲（すもう）", "meaning": "Sumo" },
  { "word": "何回も（なんかいも）", "meaning": "Berkali-kali" },
  { "word": "一回も（いっかいも）", "meaning": "Sekalipun tidak" },
  { "word": "サービス", "meaning": "Layanan / Service" },
  { "word": "ホテル", "meaning": "Hotel" },
  { "word": "紅葉（こうよう）", "meaning": "Daun musim gugur / Momiji" },
  { "word": "知ります（しります）", "meaning": "Mengetahui / Tahu" },
  { "word": "デートします", "meaning": "Berkencan" },
  { "word": "ドリアン", "meaning": "Durian" },
  { "word": "若い（わかい）", "meaning": "Muda" },
  { "word": "新鮮（しんせん）", "meaning": "Segar" },
  { "word": "電気製品（でんきせいひん）", "meaning": "Barang elektronik" },
  { "word": "お店（おみせ）", "meaning": "Toko" },
  { "word": "帽子（ぼうし）", "meaning": "Topi" },
  { "word": "売ります（うります）", "meaning": "Menjual" },
  { "word": "遊園地（ゆうえんち）", "meaning": "Taman bermain" },
  { "word": "ジェットコースター", "meaning": "Roller coaster" },
  { "word": "泊まります（とまります）", "meaning": "Menginap" },
  { "word": "人気（にんき）", "meaning": "Populer" },
  { "word": "男の人（おとこのひと）", "meaning": "Laki-laki" },
  { "word": "女の人（おんなのひと）", "meaning": "Perempuan" },
  { "word": "喫茶店（きっさてん）", "meaning": "Kedai kopi ala Jepang" },
  { "word": "飲み屋（のみや）", "meaning": "Tempat minum ala Jepang" },
  { "word": "今度（こんど）", "meaning": "Lain kali / Kali ini" },
  { "word": "一緒に（いっしょに）", "meaning": "Sama / Bersama" },
  { "word": "長い（ながい）", "meaning": "Panjang" },
  { "word": "野菜（やさい）", "meaning": "Sayur" },
  { "word": "去年（きょねん）", "meaning": "Tahun lalu" },
  { "word": "雑誌（ざっし）", "meaning": "Majalah" },
  { "word": "服（ふく）", "meaning": "Pakaian" },
  { "word": "シャツ", "meaning": "Kemeja" },
  { "word": "眼鏡（めがね）", "meaning": "Kacamata" },
  { "word": "サングラス", "meaning": "Kacamata hitam" },
  { "word": "スカート", "meaning": "Rok" },
  { "word": "ネクタイ", "meaning": "Dasi" },
  { "word": "【を】はきます", "meaning": "Memakai (bawahan)" },
  { "word": "【を】かけます", "meaning": "Memakai (kacamata)" },
  { "word": "【を】着ます（きます）", "meaning": "Memakai (atasan)" },
  { "word": "【を】します", "meaning": "Memakai (aksesoris)" },
  { "word": "【を】かぶります", "meaning": "Memakai (topi)" },
  { "word": "青い（あおい）", "meaning": "Biru" },
  { "word": "赤い（あかい）", "meaning": "Merah" },
  { "word": "黄色い（きいろい）", "meaning": "Kuning" },
  { "word": "黒い（くろい）", "meaning": "Hitam" },
  { "word": "茶色（ちゃいろ）", "meaning": "Cokelat" },
  { "word": "浴衣（ゆかた）", "meaning": "Yukata (kimono santai musim panas)" },
  { "word": "バスケットボール", "meaning": "Basket" },
  { "word": "場所（ばしょ）", "meaning": "Tempat" },
  { "word": "練習します（れんしゅうします）", "meaning": "Berlatih" },
  { "word": "どこか", "meaning": "Di suatu tempat" },
  { "word": "みんなで", "meaning": "Bersama-sama" },
  { "word": "店（みせ）", "meaning": "Toko" },
  { "word": "新鮮（しんせん）", "meaning": "Segar" },
  { "word": "先輩（せんぱい）", "meaning": "Senior" },
  { "word": "おやつ", "meaning": "Cemilan" },
  { "word": "飲み会（のみかい）", "meaning": "Pertemuan minum-minum" },
  { "word": "歩きます（あるきます）", "meaning": "Berjalan" },
  { "word": "探します（さがします）", "meaning": "Mencari" },
  { "word": "遊びます（あそびます）", "meaning": "Memainkan" },
  { "word": "材料（ざいりょう）", "meaning": "Bahan / Material" },
  { "word": "しりとり", "meaning": "Permainan kata berantai" },
  { "word": "一回も（いっかいも）", "meaning": "Sekalipun tidak" },
  { "word": "公園（こうえん）", "meaning": "Taman" },
  { "word": "試合（しあい）", "meaning": "Pertandingan" },
  { "word": "食べ放題（たべほうだい）", "meaning": "Makan sepuasnya" },
  { "word": "有名（ゆうめい）", "meaning": "Terkenal" },
  { "word": "肉（にく）", "meaning": "Daging" },
  { "word": "遊びます（あそびます）", "meaning": "Bermain" },
  { "word": "作ります（つくります）", "meaning": "Membuat" },
  { "word": "歌います（うたいます）", "meaning": "Menyanyi" },
  { "word": "おもしろい", "meaning": "Menarik" },
  { "word": "簡単（かんたん）", "meaning": "Mudah" }
		  ],
		  
		   "Lesson 14": [
	    { "word": "食券（しょっけん）", "meaning": "Kupon makanan" },
  { "word": "ドア", "meaning": "Pintu" },
  { "word": "お釣り（おつり）", "meaning": "Uang kembalian" },
  { "word": "ボタン", "meaning": "Tombol" },
  { "word": "電気（でんき）", "meaning": "Listrik / lampu" },
  { "word": "レバー", "meaning": "Tuas" },
  { "word": "【を】触ります（さわります）", "meaning": "Menyentuh" },
  { "word": "【が】開きます（あきます）", "meaning": "Terbuka (otomatis)" },
  { "word": "【が】つきます", "meaning": "Menyala" },
  { "word": "【を】回します（まわします）", "meaning": "Memutar" },
  { "word": "【が】出ます（でます）", "meaning": "Keluar" },
  { "word": "カイロ", "meaning": "Penghangat tubuh (instan)" },
  { "word": "ポケット", "meaning": "Saku" },
  { "word": "風鈴（ふうりん）", "meaning": "Lonceng angin" },
  { "word": "湯たんぽ（ゆたんぽ）", "meaning": "Botol air panas" },
  { "word": "布団（ふとん）", "meaning": "Kasur lantai tradisional Jepang" },
  { "word": "字（じ）", "meaning": "Huruf / karakter" },
  { "word": "おなかがいっぱいです", "meaning": "Saya kenyang" },
  { "word": "いただきます", "meaning": "Selamat makan (sebelum makan)" },
  { "word": "ごちそうさまでした", "meaning": "Terima kasih atas makanannya" },
  { "word": "こたつ", "meaning": "Meja pemanas (dengan selimut)" },
  { "word": "唐辛子（とうがらし）", "meaning": "Cabai merah" },
  { "word": "そうなんですか", "meaning": "Oh begitu ya?" },
  { "word": "ほら", "meaning": "Lihat! / Tuh kan!" },
  { "word": "止めます（とめます）", "meaning": "Menghentikan" },
  { "word": "シートベルト", "meaning": "Sabuk pengaman" },
  { "word": "きちんと", "meaning": "Dengan rapi / dengan benar" },
  { "word": "並びます（ならびます）", "meaning": "Berbaris" },
  { "word": "制服（せいふく）", "meaning": "Seragam" },
  { "word": "分ける（わける）", "meaning": "Membagi / memisahkan" },
  { "word": "以下（いか）", "meaning": "Di bawah ini / kurang dari" },
  { "word": "玄関（げんかん）", "meaning": "Pintu masuk / lobi rumah" },
  { "word": "バイク", "meaning": "Sepeda motor" },
  { "word": "ヘルメット", "meaning": "Helm" },
  { "word": "パスポート", "meaning": "Paspor" },
  { "word": "身分証（みぶんしょう）", "meaning": "KTP / identitas diri" },
  { "word": "料金（りょうきん）", "meaning": "Biaya / tarif" },
  { "word": "入場料（にゅうじょうりょう）", "meaning": "Biaya masuk" },
  { "word": "時給（じきゅう）", "meaning": "Upah per jam" },
  { "word": "ファストフード", "meaning": "Makanan cepat saji" },
  { "word": "便利（べんり）【な】", "meaning": "Praktis / nyaman" },
  { "word": "【と】思います（おもいます）", "meaning": "Saya pikir..." },
  { "word": "複雑（ふくざつ）【な】", "meaning": "Rumit / kompleks" },
  { "word": "おしゃれ【な】", "meaning": "Modis / bergaya" },
  { "word": "デザイン", "meaning": "Desain" },
  { "word": "自由（じゆう）", "meaning": "Kebebasan" },
  { "word": "経験（けいけん）・します", "meaning": "Pengalaman / mengalami" },
  { "word": "番組（ばんぐみ）", "meaning": "Acara (TV, radio)" },
  { "word": "ファッション", "meaning": "Mode / fesyen" },
  { "word": "～について", "meaning": "Tentang ~" },
  { "word": "化粧（けしょう）・します", "meaning": "Berdandan / merias wajah" },
  { "word": "うーん", "meaning": "Hmm... (ekspresi berpikir)" },
  { "word": "うるさい", "meaning": "Berisik" },
  { "word": "田舎（いなか）", "meaning": "Desa / kampung" },
  { "word": "都会（とかい）", "meaning": "Kota besar / perkotaan" },
  { "word": "空気（くうき）", "meaning": "Udara" },
  { "word": "フリープラン", "meaning": "Paket bebas (rencana bebas)" },
  { "word": "不便（ふべん）【な】", "meaning": "Tidak praktis / tidak nyaman" },
  { "word": "いつでも", "meaning": "Kapan saja" }
		  ],
		   "Lesson 15": [
	    { "word": "フリーマーケット", "meaning": "Pasar loak" },
  { "word": "無料（むりょう）", "meaning": "Gratis" },
  { "word": "夕方（ゆうがた）", "meaning": "Sore hari" },
  { "word": "曇り（くもり）", "meaning": "Berawan" },
  { "word": "台風（たいふう）", "meaning": "Topan" },
  { "word": "チーム", "meaning": "Tim" },
  { "word": "【に】負けます（まけます）", "meaning": "Kalah (dari)" },
  { "word": "【に】勝ちます（かちます）", "meaning": "Menang (atas)" },
  { "word": "【が】降ります（ふります）", "meaning": "Turun (hujan/salju)" },
  { "word": "【が】できます", "meaning": "Bisa, dapat terjadi" },
  { "word": "入院（にゅういん）", "meaning": "Masuk rumah sakit" },
  { "word": "心配（しんぱい）", "meaning": "Khawatir" },
  { "word": "結婚（けっこん）", "meaning": "Menikah" },
  { "word": "昔（むかし）", "meaning": "Dahulu, dulu" },
  { "word": "おめでとう", "meaning": "Selamat" },
  { "word": "地震（じしん）", "meaning": "Gempa bumi" },
  { "word": "事故（じこ）", "meaning": "Kecelakaan" },
  { "word": "【が】倒れます（たおれます）", "meaning": "Tumbang, roboh" },
  { "word": "【が】止まります（とまります）", "meaning": "Berhenti" },
  { "word": "【が】死にます（しにます）", "meaning": "Meninggal" },
  { "word": "【が】亡くなります（なくなります）", "meaning": "Wafat" },
  { "word": "【が】割れます（われます）", "meaning": "Pecah" },
  { "word": "本当（ほんとう）", "meaning": "Benar-benar" },
  { "word": "怖い（こわい）", "meaning": "Menakutkan" },
  { "word": "残念ですね（ざんねんですね）", "meaning": "Sayang sekali" },
  { "word": "けが", "meaning": "Luka/cidera" },
  { "word": "ガラス", "meaning": "Kaca" },
  { "word": "～パーセント", "meaning": "～Persen" },
  { "word": "～引き（びき）", "meaning": "～Potongan harga" },
  { "word": "ストラップ", "meaning": "Tali gantungan" },
  { "word": "風（かぜ）", "meaning": "Angin" },
  { "word": "強い（つよい）", "meaning": "Kuat" },
  { "word": "【が】晴れます（はれます）", "meaning": "Cerah" },
  { "word": "【が】やみます", "meaning": "Berhenti (hujan/salju)" },
  { "word": "きっと", "meaning": "Pasti, tentu" },
  { "word": "混みます（こみます）", "meaning": "Macet, ramai" },
  { "word": "たぶん", "meaning": "Mungkin" },
  { "word": "もし", "meaning": "Kalau, jika" },
  { "word": "急ぎます（いそぎます）", "meaning": "Bergegas, buru-buru" },
  { "word": "間に合います（まにあいます）", "meaning": "Tepat waktu, sempat" },
  { "word": "【が】集まります（あつまります）", "meaning": "Berkumpul" },
  { "word": "【が】閉まります（しまります）", "meaning": "Tertutup" },
  { "word": "【が】すきます", "meaning": "Kosong, tidak penuh" },
  { "word": "【が】落ちます（おちます）", "meaning": "Jatuh" },
  { "word": "【が】消えます（きえます）", "meaning": "Padam, hilang" },
  { "word": "【が】壊れます（こわれます）", "meaning": "Rusak" },
  { "word": "【が】汚れます（よごれます）", "meaning": "Kotor" }
		  ],
		  
    };

    vocabulary["All"] = Object.values(vocabulary).flat().filter((item, index, self) =>
      self.findIndex(i => i.word === item.word) === index
    );